# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/IIIT-D/Channel_Estimation/design_impl/least_squares/least_squares.srcs/sources_1/bd/designLS/ip/designLS_axi_dma_0_0/designLS_axi_dma_0_0.xci
# IP: The module: 'designLS_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIIT-D/Channel_Estimation/design_impl/least_squares/least_squares.srcs/sources_1/bd/designLS/ip/designLS_axi_dma_0_0/designLS_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'designLS_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/IIIT-D/Channel_Estimation/design_impl/least_squares/least_squares.srcs/sources_1/bd/designLS/ip/designLS_axi_dma_0_0/designLS_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'designLS_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/IIIT-D/Channel_Estimation/design_impl/least_squares/least_squares.srcs/sources_1/bd/designLS/ip/designLS_axi_dma_0_0/designLS_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'designLS_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/IIIT-D/Channel_Estimation/design_impl/least_squares/least_squares.srcs/sources_1/bd/designLS/ip/designLS_axi_dma_0_0/designLS_axi_dma_0_0.xci
# IP: The module: 'designLS_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIIT-D/Channel_Estimation/design_impl/least_squares/least_squares.srcs/sources_1/bd/designLS/ip/designLS_axi_dma_0_0/designLS_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'designLS_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/IIIT-D/Channel_Estimation/design_impl/least_squares/least_squares.srcs/sources_1/bd/designLS/ip/designLS_axi_dma_0_0/designLS_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'designLS_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/IIIT-D/Channel_Estimation/design_impl/least_squares/least_squares.srcs/sources_1/bd/designLS/ip/designLS_axi_dma_0_0/designLS_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'designLS_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
