# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_LSDNN/design_LSDNN.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_LSDNN || ORIG_REF_NAME==design_LSDNN} -quiet] -quiet

# IP: bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0/design_LSDNN_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_LSDNN_processing_system7_0_0 || ORIG_REF_NAME==design_LSDNN_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_LSDNN/ip/design_LSDNN_axi_dma_0_0/design_LSDNN_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_LSDNN_axi_dma_0_0 || ORIG_REF_NAME==design_LSDNN_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/design_LSDNN_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_LSDNN_axi_smc_0 || ORIG_REF_NAME==design_LSDNN_axi_smc_0} -quiet] -quiet

# IP: bd/design_LSDNN/ip/design_LSDNN_rst_ps7_0_100M_0/design_LSDNN_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_LSDNN_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_LSDNN_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_LSDNN/ip/design_LSDNN_auto_pc_0/design_LSDNN_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_LSDNN_auto_pc_0 || ORIG_REF_NAME==design_LSDNN_auto_pc_0} -quiet] -quiet

# IP: bd/design_LSDNN/ip/design_LSDNN_ps7_0_axi_periph_0/design_LSDNN_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_LSDNN_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_LSDNN_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_LSDNN/ip/design_LSDNN_LS_estimator_0_0/design_LSDNN_LS_estimator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_LSDNN_LS_estimator_0_0 || ORIG_REF_NAME==design_LSDNN_LS_estimator_0_0} -quiet] -quiet

# IP: bd/design_LSDNN/ip/design_LSDNN_DNN_up_0_0/design_LSDNN_DNN_up_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_LSDNN_DNN_up_0_0 || ORIG_REF_NAME==design_LSDNN_DNN_up_0_0} -quiet] -quiet

# XDC: bd/design_LSDNN/design_LSDNN_ooc.xdc
