# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/design_LSDNN_axi_smc_0.xci
# IP: The module: 'design_LSDNN_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/bd_db18.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_0/bd_db18_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_1/bd_db18_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_2/bd_db18_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_3/bd_db18_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_4/bd_db18_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_5/bd_db18_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_6/bd_db18_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_7/bd_db18_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_8/bd_db18_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_9/bd_db18_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_10/bd_db18_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_11/bd_db18_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_12/bd_db18_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_13/bd_db18_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_14/bd_db18_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_15/bd_db18_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_16/bd_db18_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_17/bd_db18_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_18/bd_db18_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_19/bd_db18_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_20/bd_db18_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_21/bd_db18_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_22/bd_db18_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_23/bd_db18_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_24/bd_db18_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_25/bd_db18_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_26/bd_db18_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_1/bd_db18_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_1/bd_db18_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_2/bd_db18_arsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_3/bd_db18_rsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_4/bd_db18_awsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_5/bd_db18_wsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_6/bd_db18_bsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_10/bd_db18_s00a2s_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_11/bd_db18_sarn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_12/bd_db18_srn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_16/bd_db18_s01a2s_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_17/bd_db18_sawn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_18/bd_db18_swn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_19/bd_db18_sbn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_20/bd_db18_m00s2a_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_21/bd_db18_m00arn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_22/bd_db18_m00rn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_23/bd_db18_m00awn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_24/bd_db18_m00wn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_25/bd_db18_m00bn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_LSDNN_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/design_LSDNN_axi_smc_0.xci
# IP: The module: 'design_LSDNN_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/bd_db18.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_0/bd_db18_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_1/bd_db18_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_2/bd_db18_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_3/bd_db18_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_4/bd_db18_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_5/bd_db18_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_6/bd_db18_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_7/bd_db18_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_8/bd_db18_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_9/bd_db18_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_10/bd_db18_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_11/bd_db18_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_12/bd_db18_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_13/bd_db18_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_14/bd_db18_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_15/bd_db18_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_16/bd_db18_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_17/bd_db18_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_18/bd_db18_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_19/bd_db18_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_20/bd_db18_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_21/bd_db18_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_22/bd_db18_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_23/bd_db18_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_24/bd_db18_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_25/bd_db18_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_26/bd_db18_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_1/bd_db18_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_1/bd_db18_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_2/bd_db18_arsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_3/bd_db18_rsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_4/bd_db18_awsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_5/bd_db18_wsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_6/bd_db18_bsw_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_10/bd_db18_s00a2s_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_11/bd_db18_sarn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_12/bd_db18_srn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_16/bd_db18_s01a2s_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_17/bd_db18_sawn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_18/bd_db18_swn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_19/bd_db18_sbn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_20/bd_db18_m00s2a_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_21/bd_db18_m00arn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_22/bd_db18_m00rn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_23/bd_db18_m00awn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_24/bd_db18_m00wn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_25/bd_db18_m00bn_0_ooc.xdc

# XDC: d:/IIIT-D/CEvDL/design_impl/LSDNN_2__P/LSDNN_2__P.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_LSDNN_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
