// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "reconstruct_complex_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic reconstruct_complex_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic reconstruct_complex_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> reconstruct_complex_s::ap_ST_fsm_state1 = "1";
const sc_lv<3> reconstruct_complex_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> reconstruct_complex_s::ap_ST_fsm_state7 = "100";
const bool reconstruct_complex_s::ap_const_boolean_1 = true;
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool reconstruct_complex_s::ap_const_boolean_0 = false;
const sc_lv<1> reconstruct_complex_s::ap_const_lv1_0 = "0";
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_1 = "1";
const sc_lv<1> reconstruct_complex_s::ap_const_lv1_1 = "1";
const sc_lv<6> reconstruct_complex_s::ap_const_lv6_0 = "000000";
const sc_lv<6> reconstruct_complex_s::ap_const_lv6_34 = "110100";
const sc_lv<6> reconstruct_complex_s::ap_const_lv6_1 = "1";
const sc_lv<7> reconstruct_complex_s::ap_const_lv7_34 = "110100";
const sc_lv<6> reconstruct_complex_s::ap_const_lv6_33 = "110011";
const sc_lv<16> reconstruct_complex_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_F = "1111";
const sc_lv<16> reconstruct_complex_s::ap_const_lv16_FFFF = "1111111111111111";
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_10 = "10000";
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_FFFFFFE8 = "11111111111111111111111111101000";
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_1F = "11111";
const sc_lv<5> reconstruct_complex_s::ap_const_lv5_9 = "1001";
const sc_lv<31> reconstruct_complex_s::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<16> reconstruct_complex_s::ap_const_lv16_FFE8 = "1111111111101000";
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_FFFFFFE7 = "11111111111111111111111111100111";
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_19 = "11001";
const sc_lv<8> reconstruct_complex_s::ap_const_lv8_7F = "1111111";
const sc_lv<8> reconstruct_complex_s::ap_const_lv8_7E = "1111110";
const sc_lv<8> reconstruct_complex_s::ap_const_lv8_6 = "110";
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_17 = "10111";
const sc_lv<32> reconstruct_complex_s::ap_const_lv32_2 = "10";

reconstruct_complex_s::reconstruct_complex_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_DNN_out_TDATA);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter3_reg );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( select_ln162_1_fu_735_p3 );
    sensitive << ( select_ln162_fu_728_p3 );

    SC_METHOD(thread_DNN_out_TDATA_blk_n);
    sensitive << ( DNN_out_TREADY );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter3_reg );

    SC_METHOD(thread_DNN_out_TLAST);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter3_reg );
    sensitive << ( tmp_last_V_reg_770_pp0_iter3_reg );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_DNN_out_TVALID);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter3_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_a_1_fu_535_p2);
    sensitive << ( icmp_ln947_2_fu_510_p2 );
    sensitive << ( icmp_ln947_3_fu_529_p2 );

    SC_METHOD(thread_a_fu_397_p2);
    sensitive << ( icmp_ln947_fu_372_p2 );
    sensitive << ( icmp_ln947_1_fu_391_p2 );

    SC_METHOD(thread_add_ln666_fu_169_p2);
    sensitive << ( zext_ln661_fu_160_p1 );

    SC_METHOD(thread_add_ln949_1_fu_554_p2);
    sensitive << ( trunc_ln944_1_reg_857 );

    SC_METHOD(thread_add_ln949_fu_416_p2);
    sensitive << ( trunc_ln944_reg_825 );

    SC_METHOD(thread_add_ln958_1_fu_594_p2);
    sensitive << ( sub_ln944_1_reg_851 );

    SC_METHOD(thread_add_ln958_fu_456_p2);
    sensitive << ( sub_ln944_reg_819 );

    SC_METHOD(thread_add_ln964_1_fu_703_p2);
    sensitive << ( select_ln964_1_fu_691_p3 );
    sensitive << ( sub_ln964_1_fu_698_p2 );

    SC_METHOD(thread_add_ln964_fu_663_p2);
    sensitive << ( select_ln964_fu_651_p3 );
    sensitive << ( sub_ln964_fu_658_p2 );

    SC_METHOD(thread_and_ln949_1_fu_566_p2);
    sensitive << ( p_Result_13_fu_559_p3 );
    sensitive << ( xor_ln949_1_fu_548_p2 );

    SC_METHOD(thread_and_ln949_fu_428_p2);
    sensitive << ( p_Result_7_fu_421_p3 );
    sensitive << ( xor_ln949_fu_410_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_state6_io );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_state6_io );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state6_io);
    sensitive << ( DNN_out_TREADY );
    sensitive << ( icmp_ln661_reg_751_pp0_iter3_reg );

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter4);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln661_fu_148_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_i_fu_154_p2);
    sensitive << ( i_0_reg_137 );

    SC_METHOD(thread_icmp_ln661_fu_148_p2);
    sensitive << ( i_0_reg_137 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln935_1_fu_224_p2);
    sensitive << ( y_L3_V_q1 );
    sensitive << ( icmp_ln661_reg_751 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln935_fu_186_p2);
    sensitive << ( y_L3_V_q0 );
    sensitive << ( icmp_ln661_reg_751 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln947_1_fu_391_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter2_reg );
    sensitive << ( icmp_ln935_reg_775_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( p_Result_6_fu_386_p2 );

    SC_METHOD(thread_icmp_ln947_2_fu_510_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter2_reg );
    sensitive << ( icmp_ln935_1_reg_797_pp0_iter2_reg );
    sensitive << ( tmp_14_reg_868 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_icmp_ln947_3_fu_529_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter2_reg );
    sensitive << ( icmp_ln935_1_reg_797_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( p_Result_12_fu_524_p2 );

    SC_METHOD(thread_icmp_ln947_fu_372_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter2_reg );
    sensitive << ( icmp_ln935_reg_775_pp0_iter2_reg );
    sensitive << ( tmp_10_reg_836 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_icmp_ln958_1_fu_589_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter2_reg );
    sensitive << ( icmp_ln935_1_reg_797_pp0_iter2_reg );
    sensitive << ( lsb_index_1_reg_862 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_icmp_ln958_fu_451_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln661_reg_751_pp0_iter2_reg );
    sensitive << ( icmp_ln935_reg_775_pp0_iter2_reg );
    sensitive << ( lsb_index_reg_830 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_l_1_fu_324_p3);
    sensitive << ( p_Result_19_fu_317_p3 );

    SC_METHOD(thread_l_fu_269_p3);
    sensitive << ( p_Result_16_fu_262_p3 );

    SC_METHOD(thread_lsb_index_1_fu_342_p2);
    sensitive << ( sub_ln944_1_fu_332_p2 );

    SC_METHOD(thread_lsb_index_fu_287_p2);
    sensitive << ( sub_ln944_fu_277_p2 );

    SC_METHOD(thread_lshr_ln947_1_fu_518_p2);
    sensitive << ( zext_ln947_1_fu_515_p1 );

    SC_METHOD(thread_lshr_ln947_fu_380_p2);
    sensitive << ( zext_ln947_fu_377_p1 );

    SC_METHOD(thread_lshr_ln958_1_fu_599_p2);
    sensitive << ( m_9_fu_586_p1 );
    sensitive << ( add_ln958_1_fu_594_p2 );

    SC_METHOD(thread_lshr_ln958_fu_461_p2);
    sensitive << ( m_fu_448_p1 );
    sensitive << ( add_ln958_fu_456_p2 );

    SC_METHOD(thread_m_10_fu_616_p3);
    sensitive << ( icmp_ln958_1_fu_589_p2 );
    sensitive << ( lshr_ln958_1_fu_599_p2 );
    sensitive << ( shl_ln958_1_fu_610_p2 );

    SC_METHOD(thread_m_12_fu_624_p2);
    sensitive << ( m_10_fu_616_p3 );
    sensitive << ( or_ln949_1_fu_578_p3 );

    SC_METHOD(thread_m_15_fu_648_p1);
    sensitive << ( m_s_reg_883 );

    SC_METHOD(thread_m_16_fu_688_p1);
    sensitive << ( m_3_reg_893 );

    SC_METHOD(thread_m_1_fu_478_p3);
    sensitive << ( icmp_ln958_fu_451_p2 );
    sensitive << ( lshr_ln958_fu_461_p2 );
    sensitive << ( shl_ln958_fu_472_p2 );

    SC_METHOD(thread_m_2_fu_486_p2);
    sensitive << ( m_1_fu_478_p3 );
    sensitive << ( or_ln_fu_440_p3 );

    SC_METHOD(thread_m_9_fu_586_p1);
    sensitive << ( tmp_V_9_reg_807_pp0_iter2_reg );

    SC_METHOD(thread_m_fu_448_p1);
    sensitive << ( tmp_V_7_reg_785_pp0_iter2_reg );

    SC_METHOD(thread_or_ln949_1_fu_578_p3);
    sensitive << ( or_ln949_fu_572_p2 );

    SC_METHOD(thread_or_ln949_2_fu_434_p2);
    sensitive << ( and_ln949_fu_428_p2 );
    sensitive << ( a_fu_397_p2 );

    SC_METHOD(thread_or_ln949_fu_572_p2);
    sensitive << ( and_ln949_1_fu_566_p2 );
    sensitive << ( a_1_fu_535_p2 );

    SC_METHOD(thread_or_ln_fu_440_p3);
    sensitive << ( or_ln949_2_fu_434_p2 );

    SC_METHOD(thread_p_Result_10_fu_252_p4);
    sensitive << ( tmp_V_9_fu_244_p3 );

    SC_METHOD(thread_p_Result_12_fu_524_p2);
    sensitive << ( tmp_V_9_reg_807_pp0_iter2_reg );
    sensitive << ( lshr_ln947_1_fu_518_p2 );

    SC_METHOD(thread_p_Result_13_fu_559_p3);
    sensitive << ( tmp_V_9_reg_807_pp0_iter2_reg );
    sensitive << ( add_ln949_1_fu_554_p2 );

    SC_METHOD(thread_p_Result_15_fu_192_p3);
    sensitive << ( y_L3_V_q0 );

    SC_METHOD(thread_p_Result_16_fu_262_p3);
    sensitive << ( p_Result_s_reg_792 );

    SC_METHOD(thread_p_Result_17_fu_676_p5);
    sensitive << ( m_15_fu_648_p1 );
    sensitive << ( tmp_4_fu_669_p3 );

    SC_METHOD(thread_p_Result_18_fu_230_p3);
    sensitive << ( y_L3_V_q1 );

    SC_METHOD(thread_p_Result_19_fu_317_p3);
    sensitive << ( p_Result_10_reg_814 );

    SC_METHOD(thread_p_Result_20_fu_716_p5);
    sensitive << ( m_16_fu_688_p1 );
    sensitive << ( tmp_6_fu_709_p3 );

    SC_METHOD(thread_p_Result_6_fu_386_p2);
    sensitive << ( tmp_V_7_reg_785_pp0_iter2_reg );
    sensitive << ( lshr_ln947_fu_380_p2 );

    SC_METHOD(thread_p_Result_7_fu_421_p3);
    sensitive << ( tmp_V_7_reg_785_pp0_iter2_reg );
    sensitive << ( add_ln949_fu_416_p2 );

    SC_METHOD(thread_p_Result_s_fu_214_p4);
    sensitive << ( tmp_V_7_fu_206_p3 );

    SC_METHOD(thread_select_ln162_1_fu_735_p3);
    sensitive << ( icmp_ln935_1_reg_797_pp0_iter3_reg );
    sensitive << ( p_Result_20_fu_716_p5 );

    SC_METHOD(thread_select_ln162_fu_728_p3);
    sensitive << ( icmp_ln935_reg_775_pp0_iter3_reg );
    sensitive << ( p_Result_17_fu_676_p5 );

    SC_METHOD(thread_select_ln964_1_fu_691_p3);
    sensitive << ( tmp_16_reg_898 );

    SC_METHOD(thread_select_ln964_fu_651_p3);
    sensitive << ( tmp_12_reg_888 );

    SC_METHOD(thread_shl_ln958_1_fu_610_p2);
    sensitive << ( m_9_fu_586_p1 );
    sensitive << ( sub_ln958_1_fu_605_p2 );

    SC_METHOD(thread_shl_ln958_fu_472_p2);
    sensitive << ( m_fu_448_p1 );
    sensitive << ( sub_ln958_fu_467_p2 );

    SC_METHOD(thread_sub_ln944_1_fu_332_p2);
    sensitive << ( l_1_fu_324_p3 );

    SC_METHOD(thread_sub_ln944_fu_277_p2);
    sensitive << ( l_fu_269_p3 );

    SC_METHOD(thread_sub_ln947_1_fu_362_p2);
    sensitive << ( trunc_ln947_1_fu_358_p1 );

    SC_METHOD(thread_sub_ln947_fu_307_p2);
    sensitive << ( trunc_ln947_fu_303_p1 );

    SC_METHOD(thread_sub_ln958_1_fu_605_p2);
    sensitive << ( sub_ln944_1_reg_851 );

    SC_METHOD(thread_sub_ln958_fu_467_p2);
    sensitive << ( sub_ln944_reg_819 );

    SC_METHOD(thread_sub_ln964_1_fu_698_p2);
    sensitive << ( trunc_ln943_1_reg_878_pp0_iter3_reg );

    SC_METHOD(thread_sub_ln964_fu_658_p2);
    sensitive << ( trunc_ln943_reg_846_pp0_iter3_reg );

    SC_METHOD(thread_tmp_11_fu_403_p3);
    sensitive << ( lsb_index_reg_830 );

    SC_METHOD(thread_tmp_15_fu_541_p3);
    sensitive << ( lsb_index_1_reg_862 );

    SC_METHOD(thread_tmp_4_fu_669_p3);
    sensitive << ( p_Result_15_reg_780_pp0_iter3_reg );
    sensitive << ( add_ln964_fu_663_p2 );

    SC_METHOD(thread_tmp_6_fu_709_p3);
    sensitive << ( p_Result_18_reg_802_pp0_iter3_reg );
    sensitive << ( add_ln964_1_fu_703_p2 );

    SC_METHOD(thread_tmp_V_4_fu_238_p2);
    sensitive << ( y_L3_V_q1 );

    SC_METHOD(thread_tmp_V_7_fu_206_p3);
    sensitive << ( y_L3_V_q0 );
    sensitive << ( p_Result_15_fu_192_p3 );
    sensitive << ( tmp_V_fu_200_p2 );

    SC_METHOD(thread_tmp_V_9_fu_244_p3);
    sensitive << ( y_L3_V_q1 );
    sensitive << ( p_Result_18_fu_230_p3 );
    sensitive << ( tmp_V_4_fu_238_p2 );

    SC_METHOD(thread_tmp_V_fu_200_p2);
    sensitive << ( y_L3_V_q0 );

    SC_METHOD(thread_tmp_last_V_fu_180_p2);
    sensitive << ( i_0_reg_137 );
    sensitive << ( icmp_ln661_fu_148_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_trunc_ln943_1_fu_368_p1);
    sensitive << ( l_1_fu_324_p3 );

    SC_METHOD(thread_trunc_ln943_fu_313_p1);
    sensitive << ( l_fu_269_p3 );

    SC_METHOD(thread_trunc_ln944_1_fu_338_p1);
    sensitive << ( sub_ln944_1_fu_332_p2 );

    SC_METHOD(thread_trunc_ln944_fu_283_p1);
    sensitive << ( sub_ln944_fu_277_p2 );

    SC_METHOD(thread_trunc_ln947_1_fu_358_p1);
    sensitive << ( sub_ln944_1_fu_332_p2 );

    SC_METHOD(thread_trunc_ln947_fu_303_p1);
    sensitive << ( sub_ln944_fu_277_p2 );

    SC_METHOD(thread_xor_ln949_1_fu_548_p2);
    sensitive << ( tmp_15_fu_541_p3 );

    SC_METHOD(thread_xor_ln949_fu_410_p2);
    sensitive << ( tmp_11_fu_403_p3 );

    SC_METHOD(thread_y_L3_V_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln666_fu_164_p1 );

    SC_METHOD(thread_y_L3_V_address1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( zext_ln666_1_fu_175_p1 );

    SC_METHOD(thread_y_L3_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_y_L3_V_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_zext_ln661_fu_160_p1);
    sensitive << ( i_0_reg_137 );

    SC_METHOD(thread_zext_ln666_1_fu_175_p1);
    sensitive << ( add_ln666_fu_169_p2 );

    SC_METHOD(thread_zext_ln666_fu_164_p1);
    sensitive << ( i_0_reg_137 );

    SC_METHOD(thread_zext_ln947_1_fu_515_p1);
    sensitive << ( sub_ln947_1_reg_873 );

    SC_METHOD(thread_zext_ln947_fu_377_p1);
    sensitive << ( sub_ln947_reg_841 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( icmp_ln661_fu_148_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "reconstruct_complex_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, y_L3_V_address0, "(port)y_L3_V_address0");
    sc_trace(mVcdFile, y_L3_V_ce0, "(port)y_L3_V_ce0");
    sc_trace(mVcdFile, y_L3_V_q0, "(port)y_L3_V_q0");
    sc_trace(mVcdFile, y_L3_V_address1, "(port)y_L3_V_address1");
    sc_trace(mVcdFile, y_L3_V_ce1, "(port)y_L3_V_ce1");
    sc_trace(mVcdFile, y_L3_V_q1, "(port)y_L3_V_q1");
    sc_trace(mVcdFile, DNN_out_TDATA, "(port)DNN_out_TDATA");
    sc_trace(mVcdFile, DNN_out_TVALID, "(port)DNN_out_TVALID");
    sc_trace(mVcdFile, DNN_out_TREADY, "(port)DNN_out_TREADY");
    sc_trace(mVcdFile, DNN_out_TLAST, "(port)DNN_out_TLAST");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, DNN_out_TDATA_blk_n, "DNN_out_TDATA_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln661_reg_751, "icmp_ln661_reg_751");
    sc_trace(mVcdFile, icmp_ln661_reg_751_pp0_iter3_reg, "icmp_ln661_reg_751_pp0_iter3_reg");
    sc_trace(mVcdFile, i_0_reg_137, "i_0_reg_137");
    sc_trace(mVcdFile, icmp_ln661_fu_148_p2, "icmp_ln661_fu_148_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter4, "ap_block_state6_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state6_io, "ap_block_state6_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln661_reg_751_pp0_iter1_reg, "icmp_ln661_reg_751_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln661_reg_751_pp0_iter2_reg, "icmp_ln661_reg_751_pp0_iter2_reg");
    sc_trace(mVcdFile, i_fu_154_p2, "i_fu_154_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_last_V_fu_180_p2, "tmp_last_V_fu_180_p2");
    sc_trace(mVcdFile, tmp_last_V_reg_770, "tmp_last_V_reg_770");
    sc_trace(mVcdFile, tmp_last_V_reg_770_pp0_iter1_reg, "tmp_last_V_reg_770_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_last_V_reg_770_pp0_iter2_reg, "tmp_last_V_reg_770_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_last_V_reg_770_pp0_iter3_reg, "tmp_last_V_reg_770_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln935_fu_186_p2, "icmp_ln935_fu_186_p2");
    sc_trace(mVcdFile, icmp_ln935_reg_775, "icmp_ln935_reg_775");
    sc_trace(mVcdFile, icmp_ln935_reg_775_pp0_iter2_reg, "icmp_ln935_reg_775_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln935_reg_775_pp0_iter3_reg, "icmp_ln935_reg_775_pp0_iter3_reg");
    sc_trace(mVcdFile, p_Result_15_fu_192_p3, "p_Result_15_fu_192_p3");
    sc_trace(mVcdFile, p_Result_15_reg_780, "p_Result_15_reg_780");
    sc_trace(mVcdFile, p_Result_15_reg_780_pp0_iter2_reg, "p_Result_15_reg_780_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_15_reg_780_pp0_iter3_reg, "p_Result_15_reg_780_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_V_7_fu_206_p3, "tmp_V_7_fu_206_p3");
    sc_trace(mVcdFile, tmp_V_7_reg_785, "tmp_V_7_reg_785");
    sc_trace(mVcdFile, tmp_V_7_reg_785_pp0_iter2_reg, "tmp_V_7_reg_785_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_s_fu_214_p4, "p_Result_s_fu_214_p4");
    sc_trace(mVcdFile, p_Result_s_reg_792, "p_Result_s_reg_792");
    sc_trace(mVcdFile, icmp_ln935_1_fu_224_p2, "icmp_ln935_1_fu_224_p2");
    sc_trace(mVcdFile, icmp_ln935_1_reg_797, "icmp_ln935_1_reg_797");
    sc_trace(mVcdFile, icmp_ln935_1_reg_797_pp0_iter2_reg, "icmp_ln935_1_reg_797_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln935_1_reg_797_pp0_iter3_reg, "icmp_ln935_1_reg_797_pp0_iter3_reg");
    sc_trace(mVcdFile, p_Result_18_fu_230_p3, "p_Result_18_fu_230_p3");
    sc_trace(mVcdFile, p_Result_18_reg_802, "p_Result_18_reg_802");
    sc_trace(mVcdFile, p_Result_18_reg_802_pp0_iter2_reg, "p_Result_18_reg_802_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_18_reg_802_pp0_iter3_reg, "p_Result_18_reg_802_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_V_9_fu_244_p3, "tmp_V_9_fu_244_p3");
    sc_trace(mVcdFile, tmp_V_9_reg_807, "tmp_V_9_reg_807");
    sc_trace(mVcdFile, tmp_V_9_reg_807_pp0_iter2_reg, "tmp_V_9_reg_807_pp0_iter2_reg");
    sc_trace(mVcdFile, p_Result_10_fu_252_p4, "p_Result_10_fu_252_p4");
    sc_trace(mVcdFile, p_Result_10_reg_814, "p_Result_10_reg_814");
    sc_trace(mVcdFile, sub_ln944_fu_277_p2, "sub_ln944_fu_277_p2");
    sc_trace(mVcdFile, sub_ln944_reg_819, "sub_ln944_reg_819");
    sc_trace(mVcdFile, trunc_ln944_fu_283_p1, "trunc_ln944_fu_283_p1");
    sc_trace(mVcdFile, trunc_ln944_reg_825, "trunc_ln944_reg_825");
    sc_trace(mVcdFile, lsb_index_fu_287_p2, "lsb_index_fu_287_p2");
    sc_trace(mVcdFile, lsb_index_reg_830, "lsb_index_reg_830");
    sc_trace(mVcdFile, tmp_10_reg_836, "tmp_10_reg_836");
    sc_trace(mVcdFile, sub_ln947_fu_307_p2, "sub_ln947_fu_307_p2");
    sc_trace(mVcdFile, sub_ln947_reg_841, "sub_ln947_reg_841");
    sc_trace(mVcdFile, trunc_ln943_fu_313_p1, "trunc_ln943_fu_313_p1");
    sc_trace(mVcdFile, trunc_ln943_reg_846, "trunc_ln943_reg_846");
    sc_trace(mVcdFile, trunc_ln943_reg_846_pp0_iter3_reg, "trunc_ln943_reg_846_pp0_iter3_reg");
    sc_trace(mVcdFile, sub_ln944_1_fu_332_p2, "sub_ln944_1_fu_332_p2");
    sc_trace(mVcdFile, sub_ln944_1_reg_851, "sub_ln944_1_reg_851");
    sc_trace(mVcdFile, trunc_ln944_1_fu_338_p1, "trunc_ln944_1_fu_338_p1");
    sc_trace(mVcdFile, trunc_ln944_1_reg_857, "trunc_ln944_1_reg_857");
    sc_trace(mVcdFile, lsb_index_1_fu_342_p2, "lsb_index_1_fu_342_p2");
    sc_trace(mVcdFile, lsb_index_1_reg_862, "lsb_index_1_reg_862");
    sc_trace(mVcdFile, tmp_14_reg_868, "tmp_14_reg_868");
    sc_trace(mVcdFile, sub_ln947_1_fu_362_p2, "sub_ln947_1_fu_362_p2");
    sc_trace(mVcdFile, sub_ln947_1_reg_873, "sub_ln947_1_reg_873");
    sc_trace(mVcdFile, trunc_ln943_1_fu_368_p1, "trunc_ln943_1_fu_368_p1");
    sc_trace(mVcdFile, trunc_ln943_1_reg_878, "trunc_ln943_1_reg_878");
    sc_trace(mVcdFile, trunc_ln943_1_reg_878_pp0_iter3_reg, "trunc_ln943_1_reg_878_pp0_iter3_reg");
    sc_trace(mVcdFile, m_s_reg_883, "m_s_reg_883");
    sc_trace(mVcdFile, tmp_12_reg_888, "tmp_12_reg_888");
    sc_trace(mVcdFile, m_3_reg_893, "m_3_reg_893");
    sc_trace(mVcdFile, tmp_16_reg_898, "tmp_16_reg_898");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, zext_ln666_fu_164_p1, "zext_ln666_fu_164_p1");
    sc_trace(mVcdFile, zext_ln666_1_fu_175_p1, "zext_ln666_1_fu_175_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, zext_ln661_fu_160_p1, "zext_ln661_fu_160_p1");
    sc_trace(mVcdFile, add_ln666_fu_169_p2, "add_ln666_fu_169_p2");
    sc_trace(mVcdFile, tmp_V_fu_200_p2, "tmp_V_fu_200_p2");
    sc_trace(mVcdFile, tmp_V_4_fu_238_p2, "tmp_V_4_fu_238_p2");
    sc_trace(mVcdFile, p_Result_16_fu_262_p3, "p_Result_16_fu_262_p3");
    sc_trace(mVcdFile, l_fu_269_p3, "l_fu_269_p3");
    sc_trace(mVcdFile, trunc_ln947_fu_303_p1, "trunc_ln947_fu_303_p1");
    sc_trace(mVcdFile, p_Result_19_fu_317_p3, "p_Result_19_fu_317_p3");
    sc_trace(mVcdFile, l_1_fu_324_p3, "l_1_fu_324_p3");
    sc_trace(mVcdFile, trunc_ln947_1_fu_358_p1, "trunc_ln947_1_fu_358_p1");
    sc_trace(mVcdFile, zext_ln947_fu_377_p1, "zext_ln947_fu_377_p1");
    sc_trace(mVcdFile, lshr_ln947_fu_380_p2, "lshr_ln947_fu_380_p2");
    sc_trace(mVcdFile, p_Result_6_fu_386_p2, "p_Result_6_fu_386_p2");
    sc_trace(mVcdFile, icmp_ln947_fu_372_p2, "icmp_ln947_fu_372_p2");
    sc_trace(mVcdFile, icmp_ln947_1_fu_391_p2, "icmp_ln947_1_fu_391_p2");
    sc_trace(mVcdFile, tmp_11_fu_403_p3, "tmp_11_fu_403_p3");
    sc_trace(mVcdFile, add_ln949_fu_416_p2, "add_ln949_fu_416_p2");
    sc_trace(mVcdFile, p_Result_7_fu_421_p3, "p_Result_7_fu_421_p3");
    sc_trace(mVcdFile, xor_ln949_fu_410_p2, "xor_ln949_fu_410_p2");
    sc_trace(mVcdFile, and_ln949_fu_428_p2, "and_ln949_fu_428_p2");
    sc_trace(mVcdFile, a_fu_397_p2, "a_fu_397_p2");
    sc_trace(mVcdFile, or_ln949_2_fu_434_p2, "or_ln949_2_fu_434_p2");
    sc_trace(mVcdFile, m_fu_448_p1, "m_fu_448_p1");
    sc_trace(mVcdFile, add_ln958_fu_456_p2, "add_ln958_fu_456_p2");
    sc_trace(mVcdFile, sub_ln958_fu_467_p2, "sub_ln958_fu_467_p2");
    sc_trace(mVcdFile, icmp_ln958_fu_451_p2, "icmp_ln958_fu_451_p2");
    sc_trace(mVcdFile, lshr_ln958_fu_461_p2, "lshr_ln958_fu_461_p2");
    sc_trace(mVcdFile, shl_ln958_fu_472_p2, "shl_ln958_fu_472_p2");
    sc_trace(mVcdFile, m_1_fu_478_p3, "m_1_fu_478_p3");
    sc_trace(mVcdFile, or_ln_fu_440_p3, "or_ln_fu_440_p3");
    sc_trace(mVcdFile, m_2_fu_486_p2, "m_2_fu_486_p2");
    sc_trace(mVcdFile, zext_ln947_1_fu_515_p1, "zext_ln947_1_fu_515_p1");
    sc_trace(mVcdFile, lshr_ln947_1_fu_518_p2, "lshr_ln947_1_fu_518_p2");
    sc_trace(mVcdFile, p_Result_12_fu_524_p2, "p_Result_12_fu_524_p2");
    sc_trace(mVcdFile, icmp_ln947_2_fu_510_p2, "icmp_ln947_2_fu_510_p2");
    sc_trace(mVcdFile, icmp_ln947_3_fu_529_p2, "icmp_ln947_3_fu_529_p2");
    sc_trace(mVcdFile, tmp_15_fu_541_p3, "tmp_15_fu_541_p3");
    sc_trace(mVcdFile, add_ln949_1_fu_554_p2, "add_ln949_1_fu_554_p2");
    sc_trace(mVcdFile, p_Result_13_fu_559_p3, "p_Result_13_fu_559_p3");
    sc_trace(mVcdFile, xor_ln949_1_fu_548_p2, "xor_ln949_1_fu_548_p2");
    sc_trace(mVcdFile, and_ln949_1_fu_566_p2, "and_ln949_1_fu_566_p2");
    sc_trace(mVcdFile, a_1_fu_535_p2, "a_1_fu_535_p2");
    sc_trace(mVcdFile, or_ln949_fu_572_p2, "or_ln949_fu_572_p2");
    sc_trace(mVcdFile, m_9_fu_586_p1, "m_9_fu_586_p1");
    sc_trace(mVcdFile, add_ln958_1_fu_594_p2, "add_ln958_1_fu_594_p2");
    sc_trace(mVcdFile, sub_ln958_1_fu_605_p2, "sub_ln958_1_fu_605_p2");
    sc_trace(mVcdFile, icmp_ln958_1_fu_589_p2, "icmp_ln958_1_fu_589_p2");
    sc_trace(mVcdFile, lshr_ln958_1_fu_599_p2, "lshr_ln958_1_fu_599_p2");
    sc_trace(mVcdFile, shl_ln958_1_fu_610_p2, "shl_ln958_1_fu_610_p2");
    sc_trace(mVcdFile, m_10_fu_616_p3, "m_10_fu_616_p3");
    sc_trace(mVcdFile, or_ln949_1_fu_578_p3, "or_ln949_1_fu_578_p3");
    sc_trace(mVcdFile, m_12_fu_624_p2, "m_12_fu_624_p2");
    sc_trace(mVcdFile, select_ln964_fu_651_p3, "select_ln964_fu_651_p3");
    sc_trace(mVcdFile, sub_ln964_fu_658_p2, "sub_ln964_fu_658_p2");
    sc_trace(mVcdFile, add_ln964_fu_663_p2, "add_ln964_fu_663_p2");
    sc_trace(mVcdFile, m_15_fu_648_p1, "m_15_fu_648_p1");
    sc_trace(mVcdFile, tmp_4_fu_669_p3, "tmp_4_fu_669_p3");
    sc_trace(mVcdFile, select_ln964_1_fu_691_p3, "select_ln964_1_fu_691_p3");
    sc_trace(mVcdFile, sub_ln964_1_fu_698_p2, "sub_ln964_1_fu_698_p2");
    sc_trace(mVcdFile, add_ln964_1_fu_703_p2, "add_ln964_1_fu_703_p2");
    sc_trace(mVcdFile, m_16_fu_688_p1, "m_16_fu_688_p1");
    sc_trace(mVcdFile, tmp_6_fu_709_p3, "tmp_6_fu_709_p3");
    sc_trace(mVcdFile, p_Result_17_fu_676_p5, "p_Result_17_fu_676_p5");
    sc_trace(mVcdFile, p_Result_20_fu_716_p5, "p_Result_20_fu_716_p5");
    sc_trace(mVcdFile, select_ln162_1_fu_735_p3, "select_ln162_1_fu_735_p3");
    sc_trace(mVcdFile, select_ln162_fu_728_p3, "select_ln162_fu_728_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

reconstruct_complex_s::~reconstruct_complex_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void reconstruct_complex_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln661_fu_148_p2.read()))) {
        i_0_reg_137 = i_fu_154_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_137 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln661_reg_751 = icmp_ln661_fu_148_p2.read();
        icmp_ln661_reg_751_pp0_iter1_reg = icmp_ln661_reg_751.read();
        tmp_last_V_reg_770_pp0_iter1_reg = tmp_last_V_reg_770.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln661_reg_751_pp0_iter2_reg = icmp_ln661_reg_751_pp0_iter1_reg.read();
        icmp_ln661_reg_751_pp0_iter3_reg = icmp_ln661_reg_751_pp0_iter2_reg.read();
        icmp_ln935_1_reg_797_pp0_iter2_reg = icmp_ln935_1_reg_797.read();
        icmp_ln935_1_reg_797_pp0_iter3_reg = icmp_ln935_1_reg_797_pp0_iter2_reg.read();
        icmp_ln935_reg_775_pp0_iter2_reg = icmp_ln935_reg_775.read();
        icmp_ln935_reg_775_pp0_iter3_reg = icmp_ln935_reg_775_pp0_iter2_reg.read();
        p_Result_15_reg_780_pp0_iter2_reg = p_Result_15_reg_780.read();
        p_Result_15_reg_780_pp0_iter3_reg = p_Result_15_reg_780_pp0_iter2_reg.read();
        p_Result_18_reg_802_pp0_iter2_reg = p_Result_18_reg_802.read();
        p_Result_18_reg_802_pp0_iter3_reg = p_Result_18_reg_802_pp0_iter2_reg.read();
        tmp_V_7_reg_785_pp0_iter2_reg = tmp_V_7_reg_785.read();
        tmp_V_9_reg_807_pp0_iter2_reg = tmp_V_9_reg_807.read();
        tmp_last_V_reg_770_pp0_iter2_reg = tmp_last_V_reg_770_pp0_iter1_reg.read();
        tmp_last_V_reg_770_pp0_iter3_reg = tmp_last_V_reg_770_pp0_iter2_reg.read();
        trunc_ln943_1_reg_878_pp0_iter3_reg = trunc_ln943_1_reg_878.read();
        trunc_ln943_reg_846_pp0_iter3_reg = trunc_ln943_reg_846.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln661_reg_751.read(), ap_const_lv1_0))) {
        icmp_ln935_1_reg_797 = icmp_ln935_1_fu_224_p2.read();
        icmp_ln935_reg_775 = icmp_ln935_fu_186_p2.read();
        p_Result_10_reg_814 = p_Result_10_fu_252_p4.read();
        p_Result_15_reg_780 = y_L3_V_q0.read().range(15, 15);
        p_Result_18_reg_802 = y_L3_V_q1.read().range(15, 15);
        p_Result_s_reg_792 = p_Result_s_fu_214_p4.read();
        tmp_V_7_reg_785 = tmp_V_7_fu_206_p3.read();
        tmp_V_9_reg_807 = tmp_V_9_fu_244_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln661_reg_751_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_1_reg_797.read()))) {
        lsb_index_1_reg_862 = lsb_index_1_fu_342_p2.read();
        sub_ln944_1_reg_851 = sub_ln944_1_fu_332_p2.read();
        sub_ln947_1_reg_873 = sub_ln947_1_fu_362_p2.read();
        tmp_14_reg_868 = lsb_index_1_fu_342_p2.read().range(31, 1);
        trunc_ln943_1_reg_878 = trunc_ln943_1_fu_368_p1.read();
        trunc_ln944_1_reg_857 = trunc_ln944_1_fu_338_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln661_reg_751_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_775.read()))) {
        lsb_index_reg_830 = lsb_index_fu_287_p2.read();
        sub_ln944_reg_819 = sub_ln944_fu_277_p2.read();
        sub_ln947_reg_841 = sub_ln947_fu_307_p2.read();
        tmp_10_reg_836 = lsb_index_fu_287_p2.read().range(31, 1);
        trunc_ln943_reg_846 = trunc_ln943_fu_313_p1.read();
        trunc_ln944_reg_825 = trunc_ln944_fu_283_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln661_reg_751_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_1_reg_797_pp0_iter2_reg.read()))) {
        m_3_reg_893 = m_12_fu_624_p2.read().range(31, 1);
        tmp_16_reg_898 = m_12_fu_624_p2.read().range(25, 25);
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln661_reg_751_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln935_reg_775_pp0_iter2_reg.read()))) {
        m_s_reg_883 = m_2_fu_486_p2.read().range(31, 1);
        tmp_12_reg_888 = m_2_fu_486_p2.read().range(25, 25);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln661_fu_148_p2.read()))) {
        tmp_last_V_reg_770 = tmp_last_V_fu_180_p2.read();
    }
}

void reconstruct_complex_s::thread_DNN_out_TDATA() {
    DNN_out_TDATA = esl_concat<32,32>(select_ln162_1_fu_735_p3.read(), select_ln162_fu_728_p3.read());
}

void reconstruct_complex_s::thread_DNN_out_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln661_reg_751_pp0_iter3_reg.read(), ap_const_lv1_0))) {
        DNN_out_TDATA_blk_n = DNN_out_TREADY.read();
    } else {
        DNN_out_TDATA_blk_n = ap_const_logic_1;
    }
}

void reconstruct_complex_s::thread_DNN_out_TLAST() {
    DNN_out_TLAST = tmp_last_V_reg_770_pp0_iter3_reg.read();
}

void reconstruct_complex_s::thread_DNN_out_TVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(icmp_ln661_reg_751_pp0_iter3_reg.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        DNN_out_TVALID = ap_const_logic_1;
    } else {
        DNN_out_TVALID = ap_const_logic_0;
    }
}

void reconstruct_complex_s::thread_a_1_fu_535_p2() {
    a_1_fu_535_p2 = (icmp_ln947_2_fu_510_p2.read() & icmp_ln947_3_fu_529_p2.read());
}

void reconstruct_complex_s::thread_a_fu_397_p2() {
    a_fu_397_p2 = (icmp_ln947_fu_372_p2.read() & icmp_ln947_1_fu_391_p2.read());
}

void reconstruct_complex_s::thread_add_ln666_fu_169_p2() {
    add_ln666_fu_169_p2 = (!ap_const_lv7_34.is_01() || !zext_ln661_fu_160_p1.read().is_01())? sc_lv<7>(): (sc_biguint<7>(ap_const_lv7_34) + sc_biguint<7>(zext_ln661_fu_160_p1.read()));
}

void reconstruct_complex_s::thread_add_ln949_1_fu_554_p2() {
    add_ln949_1_fu_554_p2 = (!ap_const_lv16_FFE8.is_01() || !trunc_ln944_1_reg_857.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_FFE8) + sc_biguint<16>(trunc_ln944_1_reg_857.read()));
}

void reconstruct_complex_s::thread_add_ln949_fu_416_p2() {
    add_ln949_fu_416_p2 = (!ap_const_lv16_FFE8.is_01() || !trunc_ln944_reg_825.read().is_01())? sc_lv<16>(): (sc_bigint<16>(ap_const_lv16_FFE8) + sc_biguint<16>(trunc_ln944_reg_825.read()));
}

void reconstruct_complex_s::thread_add_ln958_1_fu_594_p2() {
    add_ln958_1_fu_594_p2 = (!ap_const_lv32_FFFFFFE7.is_01() || !sub_ln944_1_reg_851.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE7) + sc_biguint<32>(sub_ln944_1_reg_851.read()));
}

void reconstruct_complex_s::thread_add_ln958_fu_456_p2() {
    add_ln958_fu_456_p2 = (!ap_const_lv32_FFFFFFE7.is_01() || !sub_ln944_reg_819.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE7) + sc_biguint<32>(sub_ln944_reg_819.read()));
}

void reconstruct_complex_s::thread_add_ln964_1_fu_703_p2() {
    add_ln964_1_fu_703_p2 = (!select_ln964_1_fu_691_p3.read().is_01() || !sub_ln964_1_fu_698_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(select_ln964_1_fu_691_p3.read()) + sc_biguint<8>(sub_ln964_1_fu_698_p2.read()));
}

void reconstruct_complex_s::thread_add_ln964_fu_663_p2() {
    add_ln964_fu_663_p2 = (!select_ln964_fu_651_p3.read().is_01() || !sub_ln964_fu_658_p2.read().is_01())? sc_lv<8>(): (sc_biguint<8>(select_ln964_fu_651_p3.read()) + sc_biguint<8>(sub_ln964_fu_658_p2.read()));
}

void reconstruct_complex_s::thread_and_ln949_1_fu_566_p2() {
    and_ln949_1_fu_566_p2 = (p_Result_13_fu_559_p3.read() & xor_ln949_1_fu_548_p2.read());
}

void reconstruct_complex_s::thread_and_ln949_fu_428_p2() {
    and_ln949_fu_428_p2 = (p_Result_7_fu_421_p3.read() & xor_ln949_fu_410_p2.read());
}

void reconstruct_complex_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void reconstruct_complex_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void reconstruct_complex_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[2];
}

void reconstruct_complex_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reconstruct_complex_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reconstruct_complex_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state6_io.read()));
}

void reconstruct_complex_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state6_io.read()));
}

void reconstruct_complex_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reconstruct_complex_s::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reconstruct_complex_s::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reconstruct_complex_s::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reconstruct_complex_s::thread_ap_block_state6_io() {
    ap_block_state6_io = (esl_seteq<1,1,1>(icmp_ln661_reg_751_pp0_iter3_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, DNN_out_TREADY.read()));
}

void reconstruct_complex_s::thread_ap_block_state6_pp0_stage0_iter4() {
    ap_block_state6_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void reconstruct_complex_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln661_fu_148_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void reconstruct_complex_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void reconstruct_complex_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void reconstruct_complex_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void reconstruct_complex_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void reconstruct_complex_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void reconstruct_complex_s::thread_i_fu_154_p2() {
    i_fu_154_p2 = (!i_0_reg_137.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i_0_reg_137.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void reconstruct_complex_s::thread_icmp_ln661_fu_148_p2() {
    icmp_ln661_fu_148_p2 = (!i_0_reg_137.read().is_01() || !ap_const_lv6_34.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_137.read() == ap_const_lv6_34);
}

void reconstruct_complex_s::thread_icmp_ln935_1_fu_224_p2() {
    icmp_ln935_1_fu_224_p2 = (!y_L3_V_q1.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(y_L3_V_q1.read() == ap_const_lv16_0);
}

void reconstruct_complex_s::thread_icmp_ln935_fu_186_p2() {
    icmp_ln935_fu_186_p2 = (!y_L3_V_q0.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(y_L3_V_q0.read() == ap_const_lv16_0);
}

void reconstruct_complex_s::thread_icmp_ln947_1_fu_391_p2() {
    icmp_ln947_1_fu_391_p2 = (!p_Result_6_fu_386_p2.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_6_fu_386_p2.read() != ap_const_lv16_0);
}

void reconstruct_complex_s::thread_icmp_ln947_2_fu_510_p2() {
    icmp_ln947_2_fu_510_p2 = (!tmp_14_reg_868.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_14_reg_868.read()) > sc_bigint<31>(ap_const_lv31_0));
}

void reconstruct_complex_s::thread_icmp_ln947_3_fu_529_p2() {
    icmp_ln947_3_fu_529_p2 = (!p_Result_12_fu_524_p2.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_12_fu_524_p2.read() != ap_const_lv16_0);
}

void reconstruct_complex_s::thread_icmp_ln947_fu_372_p2() {
    icmp_ln947_fu_372_p2 = (!tmp_10_reg_836.read().is_01() || !ap_const_lv31_0.is_01())? sc_lv<1>(): (sc_bigint<31>(tmp_10_reg_836.read()) > sc_bigint<31>(ap_const_lv31_0));
}

void reconstruct_complex_s::thread_icmp_ln958_1_fu_589_p2() {
    icmp_ln958_1_fu_589_p2 = (!lsb_index_1_reg_862.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(lsb_index_1_reg_862.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void reconstruct_complex_s::thread_icmp_ln958_fu_451_p2() {
    icmp_ln958_fu_451_p2 = (!lsb_index_reg_830.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(lsb_index_reg_830.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void reconstruct_complex_s::thread_l_1_fu_324_p3() {
    l_1_fu_324_p3 = esl_cttz<32,32>(p_Result_19_fu_317_p3.read());
}

void reconstruct_complex_s::thread_l_fu_269_p3() {
    l_fu_269_p3 = esl_cttz<32,32>(p_Result_16_fu_262_p3.read());
}

void reconstruct_complex_s::thread_lsb_index_1_fu_342_p2() {
    lsb_index_1_fu_342_p2 = (!ap_const_lv32_FFFFFFE8.is_01() || !sub_ln944_1_fu_332_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE8) + sc_biguint<32>(sub_ln944_1_fu_332_p2.read()));
}

void reconstruct_complex_s::thread_lsb_index_fu_287_p2() {
    lsb_index_fu_287_p2 = (!ap_const_lv32_FFFFFFE8.is_01() || !sub_ln944_fu_277_p2.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFE8) + sc_biguint<32>(sub_ln944_fu_277_p2.read()));
}

void reconstruct_complex_s::thread_lshr_ln947_1_fu_518_p2() {
    lshr_ln947_1_fu_518_p2 = (!zext_ln947_1_fu_515_p1.read().is_01())? sc_lv<16>(): ap_const_lv16_FFFF >> (unsigned short)zext_ln947_1_fu_515_p1.read().to_uint();
}

void reconstruct_complex_s::thread_lshr_ln947_fu_380_p2() {
    lshr_ln947_fu_380_p2 = (!zext_ln947_fu_377_p1.read().is_01())? sc_lv<16>(): ap_const_lv16_FFFF >> (unsigned short)zext_ln947_fu_377_p1.read().to_uint();
}

void reconstruct_complex_s::thread_lshr_ln958_1_fu_599_p2() {
    lshr_ln958_1_fu_599_p2 = (!add_ln958_1_fu_594_p2.read().is_01())? sc_lv<32>(): m_9_fu_586_p1.read() >> (unsigned short)add_ln958_1_fu_594_p2.read().to_uint();
}

void reconstruct_complex_s::thread_lshr_ln958_fu_461_p2() {
    lshr_ln958_fu_461_p2 = (!add_ln958_fu_456_p2.read().is_01())? sc_lv<32>(): m_fu_448_p1.read() >> (unsigned short)add_ln958_fu_456_p2.read().to_uint();
}

void reconstruct_complex_s::thread_m_10_fu_616_p3() {
    m_10_fu_616_p3 = (!icmp_ln958_1_fu_589_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln958_1_fu_589_p2.read()[0].to_bool())? lshr_ln958_1_fu_599_p2.read(): shl_ln958_1_fu_610_p2.read());
}

void reconstruct_complex_s::thread_m_12_fu_624_p2() {
    m_12_fu_624_p2 = (!m_10_fu_616_p3.read().is_01() || !or_ln949_1_fu_578_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(m_10_fu_616_p3.read()) + sc_biguint<32>(or_ln949_1_fu_578_p3.read()));
}

void reconstruct_complex_s::thread_m_15_fu_648_p1() {
    m_15_fu_648_p1 = esl_zext<32,31>(m_s_reg_883.read());
}

void reconstruct_complex_s::thread_m_16_fu_688_p1() {
    m_16_fu_688_p1 = esl_zext<32,31>(m_3_reg_893.read());
}

void reconstruct_complex_s::thread_m_1_fu_478_p3() {
    m_1_fu_478_p3 = (!icmp_ln958_fu_451_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln958_fu_451_p2.read()[0].to_bool())? lshr_ln958_fu_461_p2.read(): shl_ln958_fu_472_p2.read());
}

void reconstruct_complex_s::thread_m_2_fu_486_p2() {
    m_2_fu_486_p2 = (!m_1_fu_478_p3.read().is_01() || !or_ln_fu_440_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(m_1_fu_478_p3.read()) + sc_biguint<32>(or_ln_fu_440_p3.read()));
}

void reconstruct_complex_s::thread_m_9_fu_586_p1() {
    m_9_fu_586_p1 = esl_zext<32,16>(tmp_V_9_reg_807_pp0_iter2_reg.read());
}

void reconstruct_complex_s::thread_m_fu_448_p1() {
    m_fu_448_p1 = esl_zext<32,16>(tmp_V_7_reg_785_pp0_iter2_reg.read());
}

void reconstruct_complex_s::thread_or_ln949_1_fu_578_p3() {
    or_ln949_1_fu_578_p3 = esl_concat<31,1>(ap_const_lv31_0, or_ln949_fu_572_p2.read());
}

void reconstruct_complex_s::thread_or_ln949_2_fu_434_p2() {
    or_ln949_2_fu_434_p2 = (and_ln949_fu_428_p2.read() | a_fu_397_p2.read());
}

void reconstruct_complex_s::thread_or_ln949_fu_572_p2() {
    or_ln949_fu_572_p2 = (and_ln949_1_fu_566_p2.read() | a_1_fu_535_p2.read());
}

void reconstruct_complex_s::thread_or_ln_fu_440_p3() {
    or_ln_fu_440_p3 = esl_concat<31,1>(ap_const_lv31_0, or_ln949_2_fu_434_p2.read());
}

void reconstruct_complex_s::thread_p_Result_10_fu_252_p4() {
    p_Result_10_fu_252_p4 = tmp_V_9_fu_244_p3.read().range(0, 15);
}

void reconstruct_complex_s::thread_p_Result_12_fu_524_p2() {
    p_Result_12_fu_524_p2 = (tmp_V_9_reg_807_pp0_iter2_reg.read() & lshr_ln947_1_fu_518_p2.read());
}

void reconstruct_complex_s::thread_p_Result_13_fu_559_p3() {
    p_Result_13_fu_559_p3 = (!add_ln949_1_fu_554_p2.read().is_01() || sc_biguint<16>(add_ln949_1_fu_554_p2.read()).to_uint() >= 16)? sc_lv<1>(): tmp_V_9_reg_807_pp0_iter2_reg.read().range(sc_biguint<16>(add_ln949_1_fu_554_p2.read()).to_uint(), sc_biguint<16>(add_ln949_1_fu_554_p2.read()).to_uint());
}

void reconstruct_complex_s::thread_p_Result_15_fu_192_p3() {
    p_Result_15_fu_192_p3 = y_L3_V_q0.read().range(15, 15);
}

void reconstruct_complex_s::thread_p_Result_16_fu_262_p3() {
    p_Result_16_fu_262_p3 = esl_concat<16,16>(ap_const_lv16_FFFF, p_Result_s_reg_792.read());
}

void reconstruct_complex_s::thread_p_Result_17_fu_676_p5() {
    p_Result_17_fu_676_p5 = esl_partset<32,32,9,32,32>(m_15_fu_648_p1.read(), tmp_4_fu_669_p3.read(), ap_const_lv32_17, ap_const_lv32_1F);
}

void reconstruct_complex_s::thread_p_Result_18_fu_230_p3() {
    p_Result_18_fu_230_p3 = y_L3_V_q1.read().range(15, 15);
}

void reconstruct_complex_s::thread_p_Result_19_fu_317_p3() {
    p_Result_19_fu_317_p3 = esl_concat<16,16>(ap_const_lv16_FFFF, p_Result_10_reg_814.read());
}

void reconstruct_complex_s::thread_p_Result_20_fu_716_p5() {
    p_Result_20_fu_716_p5 = esl_partset<32,32,9,32,32>(m_16_fu_688_p1.read(), tmp_6_fu_709_p3.read(), ap_const_lv32_17, ap_const_lv32_1F);
}

void reconstruct_complex_s::thread_p_Result_6_fu_386_p2() {
    p_Result_6_fu_386_p2 = (tmp_V_7_reg_785_pp0_iter2_reg.read() & lshr_ln947_fu_380_p2.read());
}

void reconstruct_complex_s::thread_p_Result_7_fu_421_p3() {
    p_Result_7_fu_421_p3 = (!add_ln949_fu_416_p2.read().is_01() || sc_biguint<16>(add_ln949_fu_416_p2.read()).to_uint() >= 16)? sc_lv<1>(): tmp_V_7_reg_785_pp0_iter2_reg.read().range(sc_biguint<16>(add_ln949_fu_416_p2.read()).to_uint(), sc_biguint<16>(add_ln949_fu_416_p2.read()).to_uint());
}

void reconstruct_complex_s::thread_p_Result_s_fu_214_p4() {
    p_Result_s_fu_214_p4 = tmp_V_7_fu_206_p3.read().range(0, 15);
}

void reconstruct_complex_s::thread_select_ln162_1_fu_735_p3() {
    select_ln162_1_fu_735_p3 = (!icmp_ln935_1_reg_797_pp0_iter3_reg.read()[0].is_01())? sc_lv<32>(): ((icmp_ln935_1_reg_797_pp0_iter3_reg.read()[0].to_bool())? ap_const_lv32_0: p_Result_20_fu_716_p5.read());
}

void reconstruct_complex_s::thread_select_ln162_fu_728_p3() {
    select_ln162_fu_728_p3 = (!icmp_ln935_reg_775_pp0_iter3_reg.read()[0].is_01())? sc_lv<32>(): ((icmp_ln935_reg_775_pp0_iter3_reg.read()[0].to_bool())? ap_const_lv32_0: p_Result_17_fu_676_p5.read());
}

void reconstruct_complex_s::thread_select_ln964_1_fu_691_p3() {
    select_ln964_1_fu_691_p3 = (!tmp_16_reg_898.read()[0].is_01())? sc_lv<8>(): ((tmp_16_reg_898.read()[0].to_bool())? ap_const_lv8_7F: ap_const_lv8_7E);
}

void reconstruct_complex_s::thread_select_ln964_fu_651_p3() {
    select_ln964_fu_651_p3 = (!tmp_12_reg_888.read()[0].is_01())? sc_lv<8>(): ((tmp_12_reg_888.read()[0].to_bool())? ap_const_lv8_7F: ap_const_lv8_7E);
}

void reconstruct_complex_s::thread_shl_ln958_1_fu_610_p2() {
    shl_ln958_1_fu_610_p2 = (!sub_ln958_1_fu_605_p2.read().is_01())? sc_lv<32>(): m_9_fu_586_p1.read() << (unsigned short)sub_ln958_1_fu_605_p2.read().to_uint();
}

void reconstruct_complex_s::thread_shl_ln958_fu_472_p2() {
    shl_ln958_fu_472_p2 = (!sub_ln958_fu_467_p2.read().is_01())? sc_lv<32>(): m_fu_448_p1.read() << (unsigned short)sub_ln958_fu_467_p2.read().to_uint();
}

void reconstruct_complex_s::thread_sub_ln944_1_fu_332_p2() {
    sub_ln944_1_fu_332_p2 = (!ap_const_lv32_10.is_01() || !l_1_fu_324_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_10) - sc_biguint<32>(l_1_fu_324_p3.read()));
}

void reconstruct_complex_s::thread_sub_ln944_fu_277_p2() {
    sub_ln944_fu_277_p2 = (!ap_const_lv32_10.is_01() || !l_fu_269_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_10) - sc_biguint<32>(l_fu_269_p3.read()));
}

void reconstruct_complex_s::thread_sub_ln947_1_fu_362_p2() {
    sub_ln947_1_fu_362_p2 = (!ap_const_lv5_9.is_01() || !trunc_ln947_1_fu_358_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_9) - sc_biguint<5>(trunc_ln947_1_fu_358_p1.read()));
}

void reconstruct_complex_s::thread_sub_ln947_fu_307_p2() {
    sub_ln947_fu_307_p2 = (!ap_const_lv5_9.is_01() || !trunc_ln947_fu_303_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(ap_const_lv5_9) - sc_biguint<5>(trunc_ln947_fu_303_p1.read()));
}

void reconstruct_complex_s::thread_sub_ln958_1_fu_605_p2() {
    sub_ln958_1_fu_605_p2 = (!ap_const_lv32_19.is_01() || !sub_ln944_1_reg_851.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_19) - sc_biguint<32>(sub_ln944_1_reg_851.read()));
}

void reconstruct_complex_s::thread_sub_ln958_fu_467_p2() {
    sub_ln958_fu_467_p2 = (!ap_const_lv32_19.is_01() || !sub_ln944_reg_819.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_19) - sc_biguint<32>(sub_ln944_reg_819.read()));
}

void reconstruct_complex_s::thread_sub_ln964_1_fu_698_p2() {
    sub_ln964_1_fu_698_p2 = (!ap_const_lv8_6.is_01() || !trunc_ln943_1_reg_878_pp0_iter3_reg.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_6) - sc_biguint<8>(trunc_ln943_1_reg_878_pp0_iter3_reg.read()));
}

void reconstruct_complex_s::thread_sub_ln964_fu_658_p2() {
    sub_ln964_fu_658_p2 = (!ap_const_lv8_6.is_01() || !trunc_ln943_reg_846_pp0_iter3_reg.read().is_01())? sc_lv<8>(): (sc_biguint<8>(ap_const_lv8_6) - sc_biguint<8>(trunc_ln943_reg_846_pp0_iter3_reg.read()));
}

void reconstruct_complex_s::thread_tmp_11_fu_403_p3() {
    tmp_11_fu_403_p3 = lsb_index_reg_830.read().range(31, 31);
}

void reconstruct_complex_s::thread_tmp_15_fu_541_p3() {
    tmp_15_fu_541_p3 = lsb_index_1_reg_862.read().range(31, 31);
}

void reconstruct_complex_s::thread_tmp_4_fu_669_p3() {
    tmp_4_fu_669_p3 = esl_concat<1,8>(p_Result_15_reg_780_pp0_iter3_reg.read(), add_ln964_fu_663_p2.read());
}

void reconstruct_complex_s::thread_tmp_6_fu_709_p3() {
    tmp_6_fu_709_p3 = esl_concat<1,8>(p_Result_18_reg_802_pp0_iter3_reg.read(), add_ln964_1_fu_703_p2.read());
}

void reconstruct_complex_s::thread_tmp_V_4_fu_238_p2() {
    tmp_V_4_fu_238_p2 = (!ap_const_lv16_0.is_01() || !y_L3_V_q1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(y_L3_V_q1.read()));
}

void reconstruct_complex_s::thread_tmp_V_7_fu_206_p3() {
    tmp_V_7_fu_206_p3 = (!p_Result_15_fu_192_p3.read()[0].is_01())? sc_lv<16>(): ((p_Result_15_fu_192_p3.read()[0].to_bool())? tmp_V_fu_200_p2.read(): y_L3_V_q0.read());
}

void reconstruct_complex_s::thread_tmp_V_9_fu_244_p3() {
    tmp_V_9_fu_244_p3 = (!p_Result_18_fu_230_p3.read()[0].is_01())? sc_lv<16>(): ((p_Result_18_fu_230_p3.read()[0].to_bool())? tmp_V_4_fu_238_p2.read(): y_L3_V_q1.read());
}

void reconstruct_complex_s::thread_tmp_V_fu_200_p2() {
    tmp_V_fu_200_p2 = (!ap_const_lv16_0.is_01() || !y_L3_V_q0.read().is_01())? sc_lv<16>(): (sc_biguint<16>(ap_const_lv16_0) - sc_biguint<16>(y_L3_V_q0.read()));
}

void reconstruct_complex_s::thread_tmp_last_V_fu_180_p2() {
    tmp_last_V_fu_180_p2 = (!i_0_reg_137.read().is_01() || !ap_const_lv6_33.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_137.read() == ap_const_lv6_33);
}

void reconstruct_complex_s::thread_trunc_ln943_1_fu_368_p1() {
    trunc_ln943_1_fu_368_p1 = l_1_fu_324_p3.read().range(8-1, 0);
}

void reconstruct_complex_s::thread_trunc_ln943_fu_313_p1() {
    trunc_ln943_fu_313_p1 = l_fu_269_p3.read().range(8-1, 0);
}

void reconstruct_complex_s::thread_trunc_ln944_1_fu_338_p1() {
    trunc_ln944_1_fu_338_p1 = sub_ln944_1_fu_332_p2.read().range(16-1, 0);
}

void reconstruct_complex_s::thread_trunc_ln944_fu_283_p1() {
    trunc_ln944_fu_283_p1 = sub_ln944_fu_277_p2.read().range(16-1, 0);
}

void reconstruct_complex_s::thread_trunc_ln947_1_fu_358_p1() {
    trunc_ln947_1_fu_358_p1 = sub_ln944_1_fu_332_p2.read().range(5-1, 0);
}

void reconstruct_complex_s::thread_trunc_ln947_fu_303_p1() {
    trunc_ln947_fu_303_p1 = sub_ln944_fu_277_p2.read().range(5-1, 0);
}

void reconstruct_complex_s::thread_xor_ln949_1_fu_548_p2() {
    xor_ln949_1_fu_548_p2 = (tmp_15_fu_541_p3.read() ^ ap_const_lv1_1);
}

void reconstruct_complex_s::thread_xor_ln949_fu_410_p2() {
    xor_ln949_fu_410_p2 = (tmp_11_fu_403_p3.read() ^ ap_const_lv1_1);
}

void reconstruct_complex_s::thread_y_L3_V_address0() {
    y_L3_V_address0 =  (sc_lv<7>) (zext_ln666_fu_164_p1.read());
}

void reconstruct_complex_s::thread_y_L3_V_address1() {
    y_L3_V_address1 =  (sc_lv<7>) (zext_ln666_1_fu_175_p1.read());
}

void reconstruct_complex_s::thread_y_L3_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        y_L3_V_ce0 = ap_const_logic_1;
    } else {
        y_L3_V_ce0 = ap_const_logic_0;
    }
}

void reconstruct_complex_s::thread_y_L3_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        y_L3_V_ce1 = ap_const_logic_1;
    } else {
        y_L3_V_ce1 = ap_const_logic_0;
    }
}

void reconstruct_complex_s::thread_zext_ln661_fu_160_p1() {
    zext_ln661_fu_160_p1 = esl_zext<7,6>(i_0_reg_137.read());
}

void reconstruct_complex_s::thread_zext_ln666_1_fu_175_p1() {
    zext_ln666_1_fu_175_p1 = esl_zext<64,7>(add_ln666_fu_169_p2.read());
}

void reconstruct_complex_s::thread_zext_ln666_fu_164_p1() {
    zext_ln666_fu_164_p1 = esl_zext<64,6>(i_0_reg_137.read());
}

void reconstruct_complex_s::thread_zext_ln947_1_fu_515_p1() {
    zext_ln947_1_fu_515_p1 = esl_zext<16,5>(sub_ln947_1_reg_873.read());
}

void reconstruct_complex_s::thread_zext_ln947_fu_377_p1() {
    zext_ln947_fu_377_p1 = esl_zext<16,5>(sub_ln947_reg_841.read());
}

void reconstruct_complex_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln661_fu_148_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln661_fu_148_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

