# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/IIIT-D/Channel_Estimation/design_impl/LSDNN_4__WLO/LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_DNN_wlo_166_0_0/design_LSDNN_DNN_wlo_166_0_0.xci
# IP: The module: 'design_LSDNN_DNN_wlo_166_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIIT-D/Channel_Estimation/design_impl/LSDNN_4__WLO/LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_DNN_wlo_166_0_0/constraints/DNN_wlo_166_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_LSDNN_DNN_wlo_166_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/IIIT-D/Channel_Estimation/design_impl/LSDNN_4__WLO/LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_DNN_wlo_166_0_0/design_LSDNN_DNN_wlo_166_0_0.xci
# IP: The module: 'design_LSDNN_DNN_wlo_166_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/IIIT-D/Channel_Estimation/design_impl/LSDNN_4__WLO/LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_DNN_wlo_166_0_0/constraints/DNN_wlo_166_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_LSDNN_DNN_wlo_166_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
