#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : design_LSDNN.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Tue Aug 16 17:55:24 +0530 2022
# SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_LSDNN.sh [-help]
# usage: design_LSDNN.sh [-lib_map_path]
# usage: design_LSDNN.sh [-noclean_files]
# usage: design_LSDNN.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_LSDNN.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_5 processing_system7_vip_v1_0_7 lib_pkg_v1_0_2 fifo_generator_v13_2_4 lib_fifo_v1_0_13 lib_srl_fifo_v1_0_2 lib_cdc_v1_0_2 axi_datamover_v5_1_21 axi_sg_v4_1_12 axi_dma_v7_1_20 xlconstant_v1_1_6 proc_sys_reset_v5_0_13 smartconnect_v1_0 xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_15 floating_point_v7_1_8 generic_baseblocks_v2_1_0 axi_data_fifo_v2_1_18 axi_register_slice_v2_1_19 axi_protocol_converter_v2_1_19)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_LSDNN.sh - Script generated by export_simulation (Vivado v2019.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_5 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d4a8/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0/sim/design_LSDNN_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1f5a/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_4 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1f5a/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/4dac/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_21 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/e644/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_sg_v4_1_12 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/91f3/hdl/axi_sg_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_dma_v7_1_20 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/260a/hdl/axi_dma_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_dma_0_0/sim/design_LSDNN_axi_dma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/sim/bd_db18.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/66e7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_0/sim/bd_db18_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_1/sim/bd_db18_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_2/sim/bd_db18_arsw_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_3/sim/bd_db18_rsw_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_4/sim/bd_db18_awsw_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_5/sim/bd_db18_wsw_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_6/sim/bd_db18_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/f85e/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_7/sim/bd_db18_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_8/sim/bd_db18_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/7de4/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_9/sim/bd_db18_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_10/sim/bd_db18_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_11/sim/bd_db18_sarn_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_12/sim/bd_db18_srn_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_13/sim/bd_db18_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_14/sim/bd_db18_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_15/sim/bd_db18_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_16/sim/bd_db18_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_17/sim/bd_db18_sawn_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_18/sim/bd_db18_swn_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_19/sim/bd_db18_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_20/sim/bd_db18_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_21/sim/bd_db18_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_22/sim/bd_db18_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_23/sim/bd_db18_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_24/sim/bd_db18_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_25/sim/bd_db18_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b387/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/bd_0/ip/ip_26/sim/bd_db18_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_axi_smc_0/sim/design_LSDNN_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_rst_ps7_0_100M_0/sim/design_LSDNN_rst_ps7_0_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1123/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_15 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d4d2/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_8 $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/83a3/hdl/floating_point_v7_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/verilog/LS_estimator_faddhbi.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/verilog/LS_estimator_fdivkbM.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/verilog/LS_estimator_fmuljbC.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/verilog/LS_estimator_fsubibs.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/verilog/LS_estimator_preabkb.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/verilog/LS_estimator.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/ip/LS_estimator_ap_fadd_3_full_dsp_32.vhd" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/ip/LS_estimator_ap_fdiv_14_no_dsp_32.vhd" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/ip/LS_estimator_ap_fmul_2_max_dsp_32.vhd" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d2c7/hdl/ip/LS_estimator_ap_fsub_3_full_dsp_32.vhd" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_LS_estimator_0_0/sim/design_LSDNN_LS_estimator_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_denorc3C.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_fcmp_bWr.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_fpextbkb.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_LS_dac2C.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mb0s.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mbXr.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mbYs.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mbZs.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mc0C.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mc4D.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mcSB.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mcTB.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mcUB.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mcVB.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mcWB.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mcXB.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mcYC.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mac_mcZC.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_mean_c1C.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_sdiv_eOg.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_std_o_V.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168_y_L3_V.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_BIAfYi.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI0iy.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI1iI.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI2iS.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI3i2.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI4jc.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI5jm.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI6jw.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI7jG.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI8jQ.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEI9j0.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIAem.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbak.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbAo.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbbk.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbBo.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbck.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbCo.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbdk.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbDo.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbek.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbEo.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIBew.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbfk.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbFp.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbgk.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbGp.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbhl.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbHp.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbil.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbIp.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbjl.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbJp.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbkl.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbKp.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbll.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbLp.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbml.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbMq.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbnm.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbNq.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbom.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbOq.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbpm.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbPq.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbqm.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbQq.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbrm.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbRq.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbsm.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbSr.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbtn.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbTr.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbun.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbUr.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbvn.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbVr.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbwn.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbxn.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbyn.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIbzo.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEICeG.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIDeQ.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIEe0.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIFfa.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIg8j.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIGfk.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIhbi.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIHfu.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIibs.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIIfE.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIjbC.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIJfO.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIkbM.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIKfY.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIlbW.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEILf8.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEImb6.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIMgi.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIncg.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEINgs.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIocq.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIOgC.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIpcA.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIPgM.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIqcK.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIQgW.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIrcU.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIRg6.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIsc4.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIShg.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEItde.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIThq.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIudo.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIUhA.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIvdy.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIVhK.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIwdI.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIWhU.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIxdS.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIXh4.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIyd2.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIYie.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIzec.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L2_wlo_168_L1_WEIZio.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_BIAb1s.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIb2s.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIb3s.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIb4t.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIb5t.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIb6t.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIb7t.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIb8t.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIb9t.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcau.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcAy.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcbu.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcBy.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIccu.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcCy.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcdu.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcDy.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIceu.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcEy.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcfu.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcFz.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcgu.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcGz.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIchv.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcHz.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIciv.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcIz.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcjv.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcJz.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIckv.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcKz.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIclv.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcLz.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcMA.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcmv.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcNA.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcnw.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcOA.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcow.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcPA.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcpw.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcQA.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcqw.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcRA.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcrw.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcsw.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIctx.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcux.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcvx.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcwx.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcxx.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIcyx.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/L3_wlo_168_L2_WEIczy.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/normalize_wlo_168.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/normalize_wlo_168cud.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/normalize_wlo_168dEe.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/reconstruct_complex_s.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/separate_complex_wlo.v" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/verilog/DNN_wlo_168.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/ip/DNN_wlo_168_ap_fcmp_0_no_dsp_32.vhd" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/d54e/hdl/ip/DNN_wlo_168_ap_fpext_0_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_DNN_wlo_168_0_0/sim/design_LSDNN_DNN_wlo_168_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/5b9c/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/4d88/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/c83a/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/8c62/hdl" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../LSDNN_4__WLO.srcs/sources_1/bd/design_LSDNN/ip/design_LSDNN_processing_system7_0_0" +incdir+"D:/Softwares/Xilinx/Vivado/Vivado/2019.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_LSDNN/ip/design_LSDNN_auto_pc_0/sim/design_LSDNN_auto_pc_0.v" \
    "$ref_dir/../../../bd/design_LSDNN/sim/design_LSDNN.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_LSDNN xil_defaultlib.glbl -o design_LSDNN_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_LSDNN_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_LSDNN.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_LSDNN_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_LSDNN_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_LSDNN.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_LSDNN.sh [-help]\n\
Usage: design_LSDNN.sh [-lib_map_path]\n\
Usage: design_LSDNN.sh [-reset_run]\n\
Usage: design_LSDNN.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
