// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module reconstruct_complex_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        y_L3_V_address0,
        y_L3_V_ce0,
        y_L3_V_q0,
        y_L3_V_address1,
        y_L3_V_ce1,
        y_L3_V_q1,
        DNN_out_TDATA,
        DNN_out_TVALID,
        DNN_out_TREADY,
        DNN_out_TLAST
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state7 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] y_L3_V_address0;
output   y_L3_V_ce0;
input  [15:0] y_L3_V_q0;
output  [6:0] y_L3_V_address1;
output   y_L3_V_ce1;
input  [15:0] y_L3_V_q1;
output  [63:0] DNN_out_TDATA;
output   DNN_out_TVALID;
input   DNN_out_TREADY;
output  [0:0] DNN_out_TLAST;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg y_L3_V_ce0;
reg y_L3_V_ce1;
reg DNN_out_TVALID;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    DNN_out_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter4;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln661_reg_751;
reg   [0:0] icmp_ln661_reg_751_pp0_iter3_reg;
reg   [5:0] i_0_reg_137;
wire   [0:0] icmp_ln661_fu_148_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
reg    ap_block_state6_io;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln661_reg_751_pp0_iter1_reg;
reg   [0:0] icmp_ln661_reg_751_pp0_iter2_reg;
wire   [5:0] i_fu_154_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_last_V_fu_180_p2;
reg   [0:0] tmp_last_V_reg_770;
reg   [0:0] tmp_last_V_reg_770_pp0_iter1_reg;
reg   [0:0] tmp_last_V_reg_770_pp0_iter2_reg;
reg   [0:0] tmp_last_V_reg_770_pp0_iter3_reg;
wire   [0:0] icmp_ln935_fu_186_p2;
reg   [0:0] icmp_ln935_reg_775;
reg   [0:0] icmp_ln935_reg_775_pp0_iter2_reg;
reg   [0:0] icmp_ln935_reg_775_pp0_iter3_reg;
wire   [0:0] p_Result_15_fu_192_p3;
reg   [0:0] p_Result_15_reg_780;
reg   [0:0] p_Result_15_reg_780_pp0_iter2_reg;
reg   [0:0] p_Result_15_reg_780_pp0_iter3_reg;
wire   [15:0] tmp_V_7_fu_206_p3;
reg   [15:0] tmp_V_7_reg_785;
reg   [15:0] tmp_V_7_reg_785_pp0_iter2_reg;
reg   [15:0] p_Result_s_fu_214_p4;
reg   [15:0] p_Result_s_reg_792;
wire   [0:0] icmp_ln935_1_fu_224_p2;
reg   [0:0] icmp_ln935_1_reg_797;
reg   [0:0] icmp_ln935_1_reg_797_pp0_iter2_reg;
reg   [0:0] icmp_ln935_1_reg_797_pp0_iter3_reg;
wire   [0:0] p_Result_18_fu_230_p3;
reg   [0:0] p_Result_18_reg_802;
reg   [0:0] p_Result_18_reg_802_pp0_iter2_reg;
reg   [0:0] p_Result_18_reg_802_pp0_iter3_reg;
wire   [15:0] tmp_V_9_fu_244_p3;
reg   [15:0] tmp_V_9_reg_807;
reg   [15:0] tmp_V_9_reg_807_pp0_iter2_reg;
reg   [15:0] p_Result_10_fu_252_p4;
reg   [15:0] p_Result_10_reg_814;
wire   [31:0] sub_ln944_fu_277_p2;
reg   [31:0] sub_ln944_reg_819;
wire   [15:0] trunc_ln944_fu_283_p1;
reg   [15:0] trunc_ln944_reg_825;
wire   [31:0] lsb_index_fu_287_p2;
reg   [31:0] lsb_index_reg_830;
reg   [30:0] tmp_10_reg_836;
wire   [4:0] sub_ln947_fu_307_p2;
reg   [4:0] sub_ln947_reg_841;
wire   [7:0] trunc_ln943_fu_313_p1;
reg   [7:0] trunc_ln943_reg_846;
reg   [7:0] trunc_ln943_reg_846_pp0_iter3_reg;
wire   [31:0] sub_ln944_1_fu_332_p2;
reg   [31:0] sub_ln944_1_reg_851;
wire   [15:0] trunc_ln944_1_fu_338_p1;
reg   [15:0] trunc_ln944_1_reg_857;
wire   [31:0] lsb_index_1_fu_342_p2;
reg   [31:0] lsb_index_1_reg_862;
reg   [30:0] tmp_14_reg_868;
wire   [4:0] sub_ln947_1_fu_362_p2;
reg   [4:0] sub_ln947_1_reg_873;
wire   [7:0] trunc_ln943_1_fu_368_p1;
reg   [7:0] trunc_ln943_1_reg_878;
reg   [7:0] trunc_ln943_1_reg_878_pp0_iter3_reg;
reg   [30:0] m_s_reg_883;
reg   [0:0] tmp_12_reg_888;
reg   [30:0] m_3_reg_893;
reg   [0:0] tmp_16_reg_898;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
wire   [63:0] zext_ln666_fu_164_p1;
wire   [63:0] zext_ln666_1_fu_175_p1;
wire    ap_block_pp0_stage0_01001;
wire   [6:0] zext_ln661_fu_160_p1;
wire   [6:0] add_ln666_fu_169_p2;
wire   [15:0] tmp_V_fu_200_p2;
wire   [15:0] tmp_V_4_fu_238_p2;
wire   [31:0] p_Result_16_fu_262_p3;
reg   [31:0] l_fu_269_p3;
wire   [4:0] trunc_ln947_fu_303_p1;
wire   [31:0] p_Result_19_fu_317_p3;
reg   [31:0] l_1_fu_324_p3;
wire   [4:0] trunc_ln947_1_fu_358_p1;
wire   [15:0] zext_ln947_fu_377_p1;
wire   [15:0] lshr_ln947_fu_380_p2;
wire   [15:0] p_Result_6_fu_386_p2;
wire   [0:0] icmp_ln947_fu_372_p2;
wire   [0:0] icmp_ln947_1_fu_391_p2;
wire   [0:0] tmp_11_fu_403_p3;
wire   [15:0] add_ln949_fu_416_p2;
wire   [0:0] p_Result_7_fu_421_p3;
wire   [0:0] xor_ln949_fu_410_p2;
wire   [0:0] and_ln949_fu_428_p2;
wire   [0:0] a_fu_397_p2;
wire   [0:0] or_ln949_2_fu_434_p2;
wire   [31:0] m_fu_448_p1;
wire   [31:0] add_ln958_fu_456_p2;
wire   [31:0] sub_ln958_fu_467_p2;
wire   [0:0] icmp_ln958_fu_451_p2;
wire   [31:0] lshr_ln958_fu_461_p2;
wire   [31:0] shl_ln958_fu_472_p2;
wire   [31:0] m_1_fu_478_p3;
wire   [31:0] or_ln_fu_440_p3;
wire   [31:0] m_2_fu_486_p2;
wire   [15:0] zext_ln947_1_fu_515_p1;
wire   [15:0] lshr_ln947_1_fu_518_p2;
wire   [15:0] p_Result_12_fu_524_p2;
wire   [0:0] icmp_ln947_2_fu_510_p2;
wire   [0:0] icmp_ln947_3_fu_529_p2;
wire   [0:0] tmp_15_fu_541_p3;
wire   [15:0] add_ln949_1_fu_554_p2;
wire   [0:0] p_Result_13_fu_559_p3;
wire   [0:0] xor_ln949_1_fu_548_p2;
wire   [0:0] and_ln949_1_fu_566_p2;
wire   [0:0] a_1_fu_535_p2;
wire   [0:0] or_ln949_fu_572_p2;
wire   [31:0] m_9_fu_586_p1;
wire   [31:0] add_ln958_1_fu_594_p2;
wire   [31:0] sub_ln958_1_fu_605_p2;
wire   [0:0] icmp_ln958_1_fu_589_p2;
wire   [31:0] lshr_ln958_1_fu_599_p2;
wire   [31:0] shl_ln958_1_fu_610_p2;
wire   [31:0] m_10_fu_616_p3;
wire   [31:0] or_ln949_1_fu_578_p3;
wire   [31:0] m_12_fu_624_p2;
wire   [7:0] select_ln964_fu_651_p3;
wire   [7:0] sub_ln964_fu_658_p2;
wire   [7:0] add_ln964_fu_663_p2;
wire   [31:0] m_15_fu_648_p1;
wire   [8:0] tmp_4_fu_669_p3;
wire   [7:0] select_ln964_1_fu_691_p3;
wire   [7:0] sub_ln964_1_fu_698_p2;
wire   [7:0] add_ln964_1_fu_703_p2;
wire   [31:0] m_16_fu_688_p1;
wire   [8:0] tmp_6_fu_709_p3;
wire   [31:0] p_Result_17_fu_676_p5;
wire   [31:0] p_Result_20_fu_716_p5;
wire   [31:0] select_ln162_1_fu_735_p3;
wire   [31:0] select_ln162_fu_728_p3;
wire    ap_CS_fsm_state7;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln661_fu_148_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_0_reg_137 <= i_fu_154_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_reg_137 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln661_reg_751 <= icmp_ln661_fu_148_p2;
        icmp_ln661_reg_751_pp0_iter1_reg <= icmp_ln661_reg_751;
        tmp_last_V_reg_770_pp0_iter1_reg <= tmp_last_V_reg_770;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln661_reg_751_pp0_iter2_reg <= icmp_ln661_reg_751_pp0_iter1_reg;
        icmp_ln661_reg_751_pp0_iter3_reg <= icmp_ln661_reg_751_pp0_iter2_reg;
        icmp_ln935_1_reg_797_pp0_iter2_reg <= icmp_ln935_1_reg_797;
        icmp_ln935_1_reg_797_pp0_iter3_reg <= icmp_ln935_1_reg_797_pp0_iter2_reg;
        icmp_ln935_reg_775_pp0_iter2_reg <= icmp_ln935_reg_775;
        icmp_ln935_reg_775_pp0_iter3_reg <= icmp_ln935_reg_775_pp0_iter2_reg;
        p_Result_15_reg_780_pp0_iter2_reg <= p_Result_15_reg_780;
        p_Result_15_reg_780_pp0_iter3_reg <= p_Result_15_reg_780_pp0_iter2_reg;
        p_Result_18_reg_802_pp0_iter2_reg <= p_Result_18_reg_802;
        p_Result_18_reg_802_pp0_iter3_reg <= p_Result_18_reg_802_pp0_iter2_reg;
        tmp_V_7_reg_785_pp0_iter2_reg <= tmp_V_7_reg_785;
        tmp_V_9_reg_807_pp0_iter2_reg <= tmp_V_9_reg_807;
        tmp_last_V_reg_770_pp0_iter2_reg <= tmp_last_V_reg_770_pp0_iter1_reg;
        tmp_last_V_reg_770_pp0_iter3_reg <= tmp_last_V_reg_770_pp0_iter2_reg;
        trunc_ln943_1_reg_878_pp0_iter3_reg <= trunc_ln943_1_reg_878;
        trunc_ln943_reg_846_pp0_iter3_reg <= trunc_ln943_reg_846;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln661_reg_751 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln935_1_reg_797 <= icmp_ln935_1_fu_224_p2;
        icmp_ln935_reg_775 <= icmp_ln935_fu_186_p2;
        p_Result_10_reg_814 <= p_Result_10_fu_252_p4;
        p_Result_15_reg_780 <= y_L3_V_q0[32'd15];
        p_Result_18_reg_802 <= y_L3_V_q1[32'd15];
        p_Result_s_reg_792 <= p_Result_s_fu_214_p4;
        tmp_V_7_reg_785 <= tmp_V_7_fu_206_p3;
        tmp_V_9_reg_807 <= tmp_V_9_fu_244_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln661_reg_751_pp0_iter1_reg == 1'd0) & (icmp_ln935_1_reg_797 == 1'd0))) begin
        lsb_index_1_reg_862 <= lsb_index_1_fu_342_p2;
        sub_ln944_1_reg_851 <= sub_ln944_1_fu_332_p2;
        sub_ln947_1_reg_873 <= sub_ln947_1_fu_362_p2;
        tmp_14_reg_868 <= {{lsb_index_1_fu_342_p2[31:1]}};
        trunc_ln943_1_reg_878 <= trunc_ln943_1_fu_368_p1;
        trunc_ln944_1_reg_857 <= trunc_ln944_1_fu_338_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln935_reg_775 == 1'd0) & (icmp_ln661_reg_751_pp0_iter1_reg == 1'd0))) begin
        lsb_index_reg_830 <= lsb_index_fu_287_p2;
        sub_ln944_reg_819 <= sub_ln944_fu_277_p2;
        sub_ln947_reg_841 <= sub_ln947_fu_307_p2;
        tmp_10_reg_836 <= {{lsb_index_fu_287_p2[31:1]}};
        trunc_ln943_reg_846 <= trunc_ln943_fu_313_p1;
        trunc_ln944_reg_825 <= trunc_ln944_fu_283_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln661_reg_751_pp0_iter2_reg == 1'd0) & (icmp_ln935_1_reg_797_pp0_iter2_reg == 1'd0))) begin
        m_3_reg_893 <= {{m_12_fu_624_p2[31:1]}};
        tmp_16_reg_898 <= m_12_fu_624_p2[32'd25];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln935_reg_775_pp0_iter2_reg == 1'd0) & (icmp_ln661_reg_751_pp0_iter2_reg == 1'd0))) begin
        m_s_reg_883 <= {{m_2_fu_486_p2[31:1]}};
        tmp_12_reg_888 <= m_2_fu_486_p2[32'd25];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln661_fu_148_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_last_V_reg_770 <= tmp_last_V_fu_180_p2;
    end
end

always @ (*) begin
    if (((icmp_ln661_reg_751_pp0_iter3_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        DNN_out_TDATA_blk_n = DNN_out_TREADY;
    end else begin
        DNN_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln661_reg_751_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        DNN_out_TVALID = 1'b1;
    end else begin
        DNN_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln661_fu_148_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_L3_V_ce0 = 1'b1;
    end else begin
        y_L3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        y_L3_V_ce1 = 1'b1;
    end else begin
        y_L3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((icmp_ln661_fu_148_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) & ~((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((icmp_ln661_fu_148_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone)))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign DNN_out_TDATA = {{select_ln162_1_fu_735_p3}, {select_ln162_fu_728_p3}};

assign DNN_out_TLAST = tmp_last_V_reg_770_pp0_iter3_reg;

assign a_1_fu_535_p2 = (icmp_ln947_3_fu_529_p2 & icmp_ln947_2_fu_510_p2);

assign a_fu_397_p2 = (icmp_ln947_fu_372_p2 & icmp_ln947_1_fu_391_p2);

assign add_ln666_fu_169_p2 = (7'd52 + zext_ln661_fu_160_p1);

assign add_ln949_1_fu_554_p2 = ($signed(16'd65512) + $signed(trunc_ln944_1_reg_857));

assign add_ln949_fu_416_p2 = ($signed(16'd65512) + $signed(trunc_ln944_reg_825));

assign add_ln958_1_fu_594_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_1_reg_851));

assign add_ln958_fu_456_p2 = ($signed(32'd4294967271) + $signed(sub_ln944_reg_819));

assign add_ln964_1_fu_703_p2 = (select_ln964_1_fu_691_p3 + sub_ln964_1_fu_698_p2);

assign add_ln964_fu_663_p2 = (select_ln964_fu_651_p3 + sub_ln964_fu_658_p2);

assign and_ln949_1_fu_566_p2 = (xor_ln949_1_fu_548_p2 & p_Result_13_fu_559_p3);

assign and_ln949_fu_428_p2 = (xor_ln949_fu_410_p2 & p_Result_7_fu_421_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state6_io));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state6_io));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_io = ((icmp_ln661_reg_751_pp0_iter3_reg == 1'd0) & (1'b0 == DNN_out_TREADY));
end

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign i_fu_154_p2 = (i_0_reg_137 + 6'd1);

assign icmp_ln661_fu_148_p2 = ((i_0_reg_137 == 6'd52) ? 1'b1 : 1'b0);

assign icmp_ln935_1_fu_224_p2 = ((y_L3_V_q1 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln935_fu_186_p2 = ((y_L3_V_q0 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_1_fu_391_p2 = ((p_Result_6_fu_386_p2 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_2_fu_510_p2 = (($signed(tmp_14_reg_868) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln947_3_fu_529_p2 = ((p_Result_12_fu_524_p2 != 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln947_fu_372_p2 = (($signed(tmp_10_reg_836) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_1_fu_589_p2 = (($signed(lsb_index_1_reg_862) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln958_fu_451_p2 = (($signed(lsb_index_reg_830) > $signed(32'd0)) ? 1'b1 : 1'b0);


always @ (p_Result_19_fu_317_p3) begin
    if (p_Result_19_fu_317_p3[0] == 1'b1) begin
        l_1_fu_324_p3 = 32'd0;
    end else if (p_Result_19_fu_317_p3[1] == 1'b1) begin
        l_1_fu_324_p3 = 32'd1;
    end else if (p_Result_19_fu_317_p3[2] == 1'b1) begin
        l_1_fu_324_p3 = 32'd2;
    end else if (p_Result_19_fu_317_p3[3] == 1'b1) begin
        l_1_fu_324_p3 = 32'd3;
    end else if (p_Result_19_fu_317_p3[4] == 1'b1) begin
        l_1_fu_324_p3 = 32'd4;
    end else if (p_Result_19_fu_317_p3[5] == 1'b1) begin
        l_1_fu_324_p3 = 32'd5;
    end else if (p_Result_19_fu_317_p3[6] == 1'b1) begin
        l_1_fu_324_p3 = 32'd6;
    end else if (p_Result_19_fu_317_p3[7] == 1'b1) begin
        l_1_fu_324_p3 = 32'd7;
    end else if (p_Result_19_fu_317_p3[8] == 1'b1) begin
        l_1_fu_324_p3 = 32'd8;
    end else if (p_Result_19_fu_317_p3[9] == 1'b1) begin
        l_1_fu_324_p3 = 32'd9;
    end else if (p_Result_19_fu_317_p3[10] == 1'b1) begin
        l_1_fu_324_p3 = 32'd10;
    end else if (p_Result_19_fu_317_p3[11] == 1'b1) begin
        l_1_fu_324_p3 = 32'd11;
    end else if (p_Result_19_fu_317_p3[12] == 1'b1) begin
        l_1_fu_324_p3 = 32'd12;
    end else if (p_Result_19_fu_317_p3[13] == 1'b1) begin
        l_1_fu_324_p3 = 32'd13;
    end else if (p_Result_19_fu_317_p3[14] == 1'b1) begin
        l_1_fu_324_p3 = 32'd14;
    end else if (p_Result_19_fu_317_p3[15] == 1'b1) begin
        l_1_fu_324_p3 = 32'd15;
    end else if (p_Result_19_fu_317_p3[16] == 1'b1) begin
        l_1_fu_324_p3 = 32'd16;
    end else if (p_Result_19_fu_317_p3[17] == 1'b1) begin
        l_1_fu_324_p3 = 32'd17;
    end else if (p_Result_19_fu_317_p3[18] == 1'b1) begin
        l_1_fu_324_p3 = 32'd18;
    end else if (p_Result_19_fu_317_p3[19] == 1'b1) begin
        l_1_fu_324_p3 = 32'd19;
    end else if (p_Result_19_fu_317_p3[20] == 1'b1) begin
        l_1_fu_324_p3 = 32'd20;
    end else if (p_Result_19_fu_317_p3[21] == 1'b1) begin
        l_1_fu_324_p3 = 32'd21;
    end else if (p_Result_19_fu_317_p3[22] == 1'b1) begin
        l_1_fu_324_p3 = 32'd22;
    end else if (p_Result_19_fu_317_p3[23] == 1'b1) begin
        l_1_fu_324_p3 = 32'd23;
    end else if (p_Result_19_fu_317_p3[24] == 1'b1) begin
        l_1_fu_324_p3 = 32'd24;
    end else if (p_Result_19_fu_317_p3[25] == 1'b1) begin
        l_1_fu_324_p3 = 32'd25;
    end else if (p_Result_19_fu_317_p3[26] == 1'b1) begin
        l_1_fu_324_p3 = 32'd26;
    end else if (p_Result_19_fu_317_p3[27] == 1'b1) begin
        l_1_fu_324_p3 = 32'd27;
    end else if (p_Result_19_fu_317_p3[28] == 1'b1) begin
        l_1_fu_324_p3 = 32'd28;
    end else if (p_Result_19_fu_317_p3[29] == 1'b1) begin
        l_1_fu_324_p3 = 32'd29;
    end else if (p_Result_19_fu_317_p3[30] == 1'b1) begin
        l_1_fu_324_p3 = 32'd30;
    end else if (p_Result_19_fu_317_p3[31] == 1'b1) begin
        l_1_fu_324_p3 = 32'd31;
    end else begin
        l_1_fu_324_p3 = 32'd32;
    end
end


always @ (p_Result_16_fu_262_p3) begin
    if (p_Result_16_fu_262_p3[0] == 1'b1) begin
        l_fu_269_p3 = 32'd0;
    end else if (p_Result_16_fu_262_p3[1] == 1'b1) begin
        l_fu_269_p3 = 32'd1;
    end else if (p_Result_16_fu_262_p3[2] == 1'b1) begin
        l_fu_269_p3 = 32'd2;
    end else if (p_Result_16_fu_262_p3[3] == 1'b1) begin
        l_fu_269_p3 = 32'd3;
    end else if (p_Result_16_fu_262_p3[4] == 1'b1) begin
        l_fu_269_p3 = 32'd4;
    end else if (p_Result_16_fu_262_p3[5] == 1'b1) begin
        l_fu_269_p3 = 32'd5;
    end else if (p_Result_16_fu_262_p3[6] == 1'b1) begin
        l_fu_269_p3 = 32'd6;
    end else if (p_Result_16_fu_262_p3[7] == 1'b1) begin
        l_fu_269_p3 = 32'd7;
    end else if (p_Result_16_fu_262_p3[8] == 1'b1) begin
        l_fu_269_p3 = 32'd8;
    end else if (p_Result_16_fu_262_p3[9] == 1'b1) begin
        l_fu_269_p3 = 32'd9;
    end else if (p_Result_16_fu_262_p3[10] == 1'b1) begin
        l_fu_269_p3 = 32'd10;
    end else if (p_Result_16_fu_262_p3[11] == 1'b1) begin
        l_fu_269_p3 = 32'd11;
    end else if (p_Result_16_fu_262_p3[12] == 1'b1) begin
        l_fu_269_p3 = 32'd12;
    end else if (p_Result_16_fu_262_p3[13] == 1'b1) begin
        l_fu_269_p3 = 32'd13;
    end else if (p_Result_16_fu_262_p3[14] == 1'b1) begin
        l_fu_269_p3 = 32'd14;
    end else if (p_Result_16_fu_262_p3[15] == 1'b1) begin
        l_fu_269_p3 = 32'd15;
    end else if (p_Result_16_fu_262_p3[16] == 1'b1) begin
        l_fu_269_p3 = 32'd16;
    end else if (p_Result_16_fu_262_p3[17] == 1'b1) begin
        l_fu_269_p3 = 32'd17;
    end else if (p_Result_16_fu_262_p3[18] == 1'b1) begin
        l_fu_269_p3 = 32'd18;
    end else if (p_Result_16_fu_262_p3[19] == 1'b1) begin
        l_fu_269_p3 = 32'd19;
    end else if (p_Result_16_fu_262_p3[20] == 1'b1) begin
        l_fu_269_p3 = 32'd20;
    end else if (p_Result_16_fu_262_p3[21] == 1'b1) begin
        l_fu_269_p3 = 32'd21;
    end else if (p_Result_16_fu_262_p3[22] == 1'b1) begin
        l_fu_269_p3 = 32'd22;
    end else if (p_Result_16_fu_262_p3[23] == 1'b1) begin
        l_fu_269_p3 = 32'd23;
    end else if (p_Result_16_fu_262_p3[24] == 1'b1) begin
        l_fu_269_p3 = 32'd24;
    end else if (p_Result_16_fu_262_p3[25] == 1'b1) begin
        l_fu_269_p3 = 32'd25;
    end else if (p_Result_16_fu_262_p3[26] == 1'b1) begin
        l_fu_269_p3 = 32'd26;
    end else if (p_Result_16_fu_262_p3[27] == 1'b1) begin
        l_fu_269_p3 = 32'd27;
    end else if (p_Result_16_fu_262_p3[28] == 1'b1) begin
        l_fu_269_p3 = 32'd28;
    end else if (p_Result_16_fu_262_p3[29] == 1'b1) begin
        l_fu_269_p3 = 32'd29;
    end else if (p_Result_16_fu_262_p3[30] == 1'b1) begin
        l_fu_269_p3 = 32'd30;
    end else if (p_Result_16_fu_262_p3[31] == 1'b1) begin
        l_fu_269_p3 = 32'd31;
    end else begin
        l_fu_269_p3 = 32'd32;
    end
end

assign lsb_index_1_fu_342_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_1_fu_332_p2));

assign lsb_index_fu_287_p2 = ($signed(32'd4294967272) + $signed(sub_ln944_fu_277_p2));

assign lshr_ln947_1_fu_518_p2 = 16'd65535 >> zext_ln947_1_fu_515_p1;

assign lshr_ln947_fu_380_p2 = 16'd65535 >> zext_ln947_fu_377_p1;

assign lshr_ln958_1_fu_599_p2 = m_9_fu_586_p1 >> add_ln958_1_fu_594_p2;

assign lshr_ln958_fu_461_p2 = m_fu_448_p1 >> add_ln958_fu_456_p2;

assign m_10_fu_616_p3 = ((icmp_ln958_1_fu_589_p2[0:0] === 1'b1) ? lshr_ln958_1_fu_599_p2 : shl_ln958_1_fu_610_p2);

assign m_12_fu_624_p2 = (m_10_fu_616_p3 + or_ln949_1_fu_578_p3);

assign m_15_fu_648_p1 = m_s_reg_883;

assign m_16_fu_688_p1 = m_3_reg_893;

assign m_1_fu_478_p3 = ((icmp_ln958_fu_451_p2[0:0] === 1'b1) ? lshr_ln958_fu_461_p2 : shl_ln958_fu_472_p2);

assign m_2_fu_486_p2 = (m_1_fu_478_p3 + or_ln_fu_440_p3);

assign m_9_fu_586_p1 = tmp_V_9_reg_807_pp0_iter2_reg;

assign m_fu_448_p1 = tmp_V_7_reg_785_pp0_iter2_reg;

assign or_ln949_1_fu_578_p3 = {{31'd0}, {or_ln949_fu_572_p2}};

assign or_ln949_2_fu_434_p2 = (and_ln949_fu_428_p2 | a_fu_397_p2);

assign or_ln949_fu_572_p2 = (and_ln949_1_fu_566_p2 | a_1_fu_535_p2);

assign or_ln_fu_440_p3 = {{31'd0}, {or_ln949_2_fu_434_p2}};

integer ap_tvar_int_0;

always @ (tmp_V_9_fu_244_p3) begin
    for (ap_tvar_int_0 = 16 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 15 - 0) begin
            p_Result_10_fu_252_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_10_fu_252_p4[ap_tvar_int_0] = tmp_V_9_fu_244_p3[15 - ap_tvar_int_0];
        end
    end
end

assign p_Result_12_fu_524_p2 = (tmp_V_9_reg_807_pp0_iter2_reg & lshr_ln947_1_fu_518_p2);

assign p_Result_13_fu_559_p3 = tmp_V_9_reg_807_pp0_iter2_reg[add_ln949_1_fu_554_p2];

assign p_Result_15_fu_192_p3 = y_L3_V_q0[32'd15];

assign p_Result_16_fu_262_p3 = {{16'd65535}, {p_Result_s_reg_792}};

assign p_Result_17_fu_676_p5 = {{tmp_4_fu_669_p3}, {m_15_fu_648_p1[22:0]}};

assign p_Result_18_fu_230_p3 = y_L3_V_q1[32'd15];

assign p_Result_19_fu_317_p3 = {{16'd65535}, {p_Result_10_reg_814}};

assign p_Result_20_fu_716_p5 = {{tmp_6_fu_709_p3}, {m_16_fu_688_p1[22:0]}};

assign p_Result_6_fu_386_p2 = (tmp_V_7_reg_785_pp0_iter2_reg & lshr_ln947_fu_380_p2);

assign p_Result_7_fu_421_p3 = tmp_V_7_reg_785_pp0_iter2_reg[add_ln949_fu_416_p2];

integer ap_tvar_int_1;

always @ (tmp_V_7_fu_206_p3) begin
    for (ap_tvar_int_1 = 16 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 15 - 0) begin
            p_Result_s_fu_214_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            p_Result_s_fu_214_p4[ap_tvar_int_1] = tmp_V_7_fu_206_p3[15 - ap_tvar_int_1];
        end
    end
end

assign select_ln162_1_fu_735_p3 = ((icmp_ln935_1_reg_797_pp0_iter3_reg[0:0] === 1'b1) ? 32'd0 : p_Result_20_fu_716_p5);

assign select_ln162_fu_728_p3 = ((icmp_ln935_reg_775_pp0_iter3_reg[0:0] === 1'b1) ? 32'd0 : p_Result_17_fu_676_p5);

assign select_ln964_1_fu_691_p3 = ((tmp_16_reg_898[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign select_ln964_fu_651_p3 = ((tmp_12_reg_888[0:0] === 1'b1) ? 8'd127 : 8'd126);

assign shl_ln958_1_fu_610_p2 = m_9_fu_586_p1 << sub_ln958_1_fu_605_p2;

assign shl_ln958_fu_472_p2 = m_fu_448_p1 << sub_ln958_fu_467_p2;

assign sub_ln944_1_fu_332_p2 = (32'd16 - l_1_fu_324_p3);

assign sub_ln944_fu_277_p2 = (32'd16 - l_fu_269_p3);

assign sub_ln947_1_fu_362_p2 = (5'd9 - trunc_ln947_1_fu_358_p1);

assign sub_ln947_fu_307_p2 = (5'd9 - trunc_ln947_fu_303_p1);

assign sub_ln958_1_fu_605_p2 = (32'd25 - sub_ln944_1_reg_851);

assign sub_ln958_fu_467_p2 = (32'd25 - sub_ln944_reg_819);

assign sub_ln964_1_fu_698_p2 = (8'd6 - trunc_ln943_1_reg_878_pp0_iter3_reg);

assign sub_ln964_fu_658_p2 = (8'd6 - trunc_ln943_reg_846_pp0_iter3_reg);

assign tmp_11_fu_403_p3 = lsb_index_reg_830[32'd31];

assign tmp_15_fu_541_p3 = lsb_index_1_reg_862[32'd31];

assign tmp_4_fu_669_p3 = {{p_Result_15_reg_780_pp0_iter3_reg}, {add_ln964_fu_663_p2}};

assign tmp_6_fu_709_p3 = {{p_Result_18_reg_802_pp0_iter3_reg}, {add_ln964_1_fu_703_p2}};

assign tmp_V_4_fu_238_p2 = (16'd0 - y_L3_V_q1);

assign tmp_V_7_fu_206_p3 = ((p_Result_15_fu_192_p3[0:0] === 1'b1) ? tmp_V_fu_200_p2 : y_L3_V_q0);

assign tmp_V_9_fu_244_p3 = ((p_Result_18_fu_230_p3[0:0] === 1'b1) ? tmp_V_4_fu_238_p2 : y_L3_V_q1);

assign tmp_V_fu_200_p2 = (16'd0 - y_L3_V_q0);

assign tmp_last_V_fu_180_p2 = ((i_0_reg_137 == 6'd51) ? 1'b1 : 1'b0);

assign trunc_ln943_1_fu_368_p1 = l_1_fu_324_p3[7:0];

assign trunc_ln943_fu_313_p1 = l_fu_269_p3[7:0];

assign trunc_ln944_1_fu_338_p1 = sub_ln944_1_fu_332_p2[15:0];

assign trunc_ln944_fu_283_p1 = sub_ln944_fu_277_p2[15:0];

assign trunc_ln947_1_fu_358_p1 = sub_ln944_1_fu_332_p2[4:0];

assign trunc_ln947_fu_303_p1 = sub_ln944_fu_277_p2[4:0];

assign xor_ln949_1_fu_548_p2 = (tmp_15_fu_541_p3 ^ 1'd1);

assign xor_ln949_fu_410_p2 = (tmp_11_fu_403_p3 ^ 1'd1);

assign y_L3_V_address0 = zext_ln666_fu_164_p1;

assign y_L3_V_address1 = zext_ln666_1_fu_175_p1;

assign zext_ln661_fu_160_p1 = i_0_reg_137;

assign zext_ln666_1_fu_175_p1 = add_ln666_fu_169_p2;

assign zext_ln666_fu_164_p1 = i_0_reg_137;

assign zext_ln947_1_fu_515_p1 = sub_ln947_1_reg_873;

assign zext_ln947_fu_377_p1 = sub_ln947_reg_841;

endmodule //reconstruct_complex_s
